### ISSUE TITLE
Combat screen, terrain music is played during the combat

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4557] opened 2021-11-05 19:04 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the terrain music is played during the combat.

In fheroes2:

Activate the sound of the video.

https://user-images.githubusercontent.com/43583994/140564637-69d97357-8345-46ad-8326-b3431cf81490.mp4

### Save file

Here is the save file:
[Before combat terrain music_.zip](https://github.com/ihhub/fheroes2/files/7488344/Before.combat.terrain.music_.zip)

### Additional info

Game started with version 0.9.8 4544 and continued with version 0.9.9 4551.

**Comment by oleg-derevenetz** [comment] 2021-11-05 20:45
Regression after #4543.

**Comment by vincent-grosbois** [comment] 2021-11-05 21:54
that sucks... I'll try to see if I can fix it without having to revert

**Comment by oleg-derevenetz** [comment] 2021-11-05 22:01
@vincent-grosbois this PR is not included into 0.9.9, so no hurry here.

**Comment by vincent-grosbois** [comment] 2021-11-05 22:34
@oleg-derevenetz 
I couldn't reproduce it but I based on the video it seems that when the "prebattle music" plays, the game music isn't stopped
Based on this, it seems that it's due to the call to sync() in AGG::PlaySound that is probably erasing the "stop music" task that couldn't be dequeued in time

**Comment by zenseii** [comment] 2021-11-07 05:32
I can add that the same happens in Battle Only mode, where you'll keep hearing the Main Menu theme.

**Comment by oleg-derevenetz** [comment] 2021-11-09 15:31
I believe we can consider this as fixed by #4558.

**Closed by oleg-derevenetz** 2021-11-09 15:31 UTC
Labels: bug, sound, regression
