### ISSUE TITLE
Adventure map, the chance of joining neutral creatures

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2817] opened 2021-02-17 19:01 UTC
Wandering mummies are willing to join my not really strong army.
![image](https://user-images.githubusercontent.com/55348946/108254466-19e86780-716c-11eb-83f4-3e33b10d728c.png)
![image](https://user-images.githubusercontent.com/55348946/108253819-418b0000-716b-11eb-9827-168b6c8ff52d.png)
[Join army.zip](https://github.com/ihhub/fheroes2/files/5997965/Join.army.zip)

**Comment by LeHerosInconnu** [comment] 2021-02-17 19:57
Hello @Branikolog,

Some wandering troops are willing to join a hero no matter what.
(A certain percentage of all wandering troops on the adventure map is marked as "always join the hero").

Neither the strength of the hero's army nor any other criteria is taken into account.

These wandering troops want to travel and see the country (they want to be really wandering) and finally leave this place where they have always lived. :D

**Comment by Branikolog** [comment] 2021-02-18 06:20
@LeHerosInconnu

> A certain percentage of all wandering troops on the adventure map is marked as "always join the hero"

Even if hero has no army? O_o

**Comment by LeHerosInconnu** [comment] 2021-02-18 19:42
@Branikolog.

> @LeHerosInconnu
> 
> > A certain percentage of all wandering troops on the adventure map is marked as "always join the hero"
> 
> Even if hero has no army? O_o

I tried to reproduce my remark in Heroes 2 and I didn't succeed.
Certainly that should not be the case, and it was a dream. :D

There is certainly a condition of strength of the hero's army that must be taken into account.

Sorry for my erroneous information. :)

**Comment by Branikolog** [comment] 2021-02-18 19:49
No problem.)
One question was asked at one of our social pages...
Can monsters, that appear during "week of" join hero? On what conditions? Does Diplomacy skill required, or they could join hero army for free?

**Comment by LeHerosInconnu** [comment] 2021-02-18 20:05
Hello @Branikolog,

> No problem.)
> One question was asked at one of our social pages...
> Can monsters, that appear during "week of" join hero? On what conditions? Does Diplomacy skill required, or they could join hero army for free?

Yes, they can join the hero.
Not sure if they can join for free, :) (I think so) but with diplomacy, a powerful army and a strong economy, it is possible to recruit them.
But beware, it's a choice to be made if the map is poor in gold, because it can become expensive quickly and it won't necessarily be very powerful troops compared to the troops that could be recruited in a castle.
The advantage is that they are available where the hero is, no need to return to the castle or organize a relay with other heroes.
This is an interesting strategic choice to be made.

**Closed** 2021-08-04 12:25 UTC
Labels: bug, help wanted, logic
