### ISSUE TITLE
Cannot attack an allied player

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1321] opened 2020-08-23 07:42 UTC
In fheroes2, it is not possible to attack an allied player (heroes and castles) or capture a resource generator from an allied player.
In the original game, this is possible.

**Comment by idshibanov** [comment] 2020-08-23 18:04
Should ally AI attack player and capture your mines too? Original behaviour is flawed and should never be a default.

**Comment by LeHerosInconnu** [comment] 2020-08-23 19:08
@idshibanov.

There may be a scenario where the AI ally player has captured the only neutral castle where it was possible to build a shipyard to build a boat and thus reach other AI opponents located in a remote land only accessible by the ocean, and the scenario becomes impossible to complete.

**Comment by idshibanov** [comment] 2020-08-23 19:18
I think the blame would be on a mapmaker in such case. Can't think of any original map or campaign where this will be an issue. Summon boat exists too.

We could add an option "allow to break alliances". It should be worded like that, with a possible warning before attack or re-capture. Then provoked AI can attack back.

**Comment by idshibanov** [comment] 2020-08-23 19:24
I think alliance logic was added in the original game to allow AI work together against the player in the campaign. It was never polished and hasn't worked well in case of AI + player.

**Comment by LeHerosInconnu** [comment] 2020-08-23 19:55
@idshibanov.

> I think the blame would be on a mapmaker in such case. Can't think of any original map or campaign where this will be an issue. Summon boat exists too.

The majority of scenarios created for Heroes 2 were designed long before the appearance of fheroes2.
The map creators were therefore unable to take into account the differences in operation with the original game.

In the original campaigns and in the original scenarios, I don't think that's actually a problem.
But for other scenarios this may be the case, although I can't name one right now. :)

In Heroes 2, the Summon Boat spell does not create a boat, there must be a neutral boat on the map or the player must build a shipyard and then build a boat in order to use the spell.

> We could add an option "allow to break alliances". It should be worded like that, with a possible warning before attack or re-capture. Then provoked AI can attack back.

 This option would be nice, and the improved AI fighting back would be awesome. :)
So the player has to make a choice.

> I think alliance logic was added in the original game to allow AI work together against the player in the campaign. It was never polished and hasn't worked well in case of AI + player.

AI allied heroes can sometimes be seen fighting with each other.
This happens when an allied hero is positioned on a square on the adventure map where the other hero has planned to go or pass during his movement.
Or even when it's an AI allied human player hero that's on the planned path.

**Comment by ihhub** [comment] 2024-04-13 05:01
Closing this issue as duplicate of #8432

**Closed by ihhub** 2024-04-13 05:01 UTC
Labels: question
