### ISSUE TITLE
Scenario, scenario settings are not respected

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2010] opened 2020-10-15 18:08 UTC
In fheroes2, scenario settings are not respected.

In this scenario, all opposing heroes (green player) are set to "Patrol" and "Stand still" mode.
However, some of these heroes move during the AI turn.

In this scenario, the "Start with hero in each player's castle" box is unchecked.
However, at the start of the scenario, the blue player has a second hero located in his starting castle.

In fheroes2:

![Scenario settings fh2 01](https://user-images.githubusercontent.com/43583994/96168930-bdf1a600-0f21-11eb-9582-a9baf02fed53.png)

![Scenario settings fh2 02](https://user-images.githubusercontent.com/43583994/96168939-bfbb6980-0f21-11eb-8468-68a5fd91e52d.png)

![Scenario settings fh2 03](https://user-images.githubusercontent.com/43583994/96168949-c0ec9680-0f21-11eb-9629-2730fadccbf5.png)

![Scenario settings fh2 04](https://user-images.githubusercontent.com/43583994/96168957-c21dc380-0f21-11eb-8976-db2dc2dace7d.png)

Here are the save and test scenario files:
[Test music start combat 01.zip](https://github.com/ihhub/fheroes2/files/5386889/Test.music.start.combat.01.zip)

**Comment by idshibanov** [comment] 2020-10-17 16:54
> In this scenario, the "Start with hero in each player's castle" box is unchecked.
> However, at the start of the scenario, the blue player has a second hero located in his starting castle.

Couldn't reproduce this part of the issue on master branch build. Tried the map you attached as well as another custom one checking/unchecking the starting hero checkbox. Code for it is there and looks like it works as intended.

Patrol mode will be fixed.

**Comment by LeHerosInconnu** [comment] 2020-10-17 20:15
@idshibanov.

> > In this scenario, the "Start with hero in each player's castle" box is unchecked.
> > However, at the start of the scenario, the blue player has a second hero located in his starting castle.
> 
> Couldn't reproduce this part of the issue on master branch build. Tried the map you attached as well as another custom one checking/unchecking the starting hero checkbox. Code for it is there and looks like it works as intended.
> 
> Patrol mode will be fixed.

Okay.
I will do some tests later with the latest version of the moment.

**Closed** 2020-10-18 08:09 UTC
Labels: AI, bug, logic

**Comment by LeHerosInconnu** [comment] 2020-10-18 16:26
> @idshibanov.
> 
> > > In this scenario, the "Start with hero in each player's castle" box is unchecked.
> > > However, at the start of the scenario, the blue player has a second hero located in his starting castle.
> > 
> > 
> > Couldn't reproduce this part of the issue on master branch build. Tried the map you attached as well as another custom one checking/unchecking the starting hero checkbox. Code for it is there and looks like it works as intended.
> > Patrol mode will be fixed.
> 
> Okay.
> I will do some tests later with the latest version of the moment.

I did some tests with fheroes2 version 0.8.2 2036.
It seems to be working fine, the bug did not occur.
