### ISSUE TITLE
mouse hot keys

### ISSUE THREAD

**Issue by mataski** [ihhub/fheroes2#6705] opened 2023-02-24 00:22 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

key bindings for mouse do not work, e.g. next hero or next town cannot bind to mouse4/mouse5 (the buttons the mouse side under your thumb)

### Describe the possible solution

add support to mouse4/mouse5

**Comment by Mr-Bajs** [comment] 2023-02-24 19:06
Duplicate of https://github.com/ihhub/fheroes2/issues/6580

**Comment by ihhub** [comment] 2023-03-31 15:26
Closing as a duplicated issue.

**Closed by ihhub** 2023-03-31 15:26 UTC
Labels: improvement, ui
