### ISSUE TITLE
The bug with starting screen in window and fullscreen is different...

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#7943] opened 2023-10-14 19:02 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In full screen I can see troops the hero has:
![image](https://github.com/ihhub/fheroes2/assets/145407420/e25269f9-4a7a-424f-b9f2-9f7532a2d758)

In window I can see the month 1, week 1, day:
![image](https://github.com/ihhub/fheroes2/assets/145407420/b9811de7-978a-4834-af47-a362b50145ae)

### Save file

No save file or video is needed here, I think.

**Comment by oleg-derevenetz** [comment] 2023-10-14 19:20
Well, that's because the resolution in windowed mode is clearly less than in fullscreen mode, so there is just no room both for in-game date and troops at the same time. I don't see how this is a "bug".

**Comment by fheroes2bugs** [comment] 2023-10-14 20:22
> Well, that's because the resolution in windowed mode is clearly less than in fullscreen mode, so there is just no room both for in-game date and troops at the same time. I don't see how this is a "bug".

I agree, just thinking, can be  in window-mode text "month, window, day" be more compressed, to add information about monsters? Could try different types of compressions, may be.

**Comment by oleg-derevenetz** [comment] 2023-10-14 20:32
> I agree, just thinking, can be in window-mode text "month, window, day" be more compressed, to add information about monsters? Could try different types of compressions, may be.

This UI replicates the UI of the original game. The updated UI used at a higher resolution is an extension/improvement over the original game. Those who wish can simply use a higher resolution and see everything at once without all these tricks.

**Comment by ihhub** [comment] 2023-10-15 00:13
I am closing this issue as this is not a bug at all as explained by @oleg-derevenetz .

**Closed by ihhub** 2023-10-15 00:13 UTC
Labels: bug

**Comment by fheroes2bugs** [comment] 2023-10-15 12:38
Trying different resolutions. In some of them, information about monster could easily be added:

![image](https://github.com/ihhub/fheroes2/assets/145407420/93b8b023-cd94-4a27-a4a1-96c354b3b7d0)

![image](https://github.com/ihhub/fheroes2/assets/145407420/1f9e17a1-11c6-4c2c-88e0-c507b2e09807)

**Comment by Branikolog** [comment] 2023-10-15 14:25
Hi, @fheroes2bugs !
Actually, there's a compromise between hero/castle lists and the size of status bar.
For some resolutions there could possibly 2 info boxes be placed in a status bar. 
![Status +res ](https://github.com/ihhub/fheroes2/assets/55348946/447535fd-dab7-4b85-944d-8473370d99d6)

But other resolutions have larger heroes/castles panel and there's no place for additional army info:
![image](https://github.com/ihhub/fheroes2/assets/55348946/0af1b438-95aa-4164-87df-b5981ef6adc3)

I'm not sure, if the number of heroes/castle could be adjusted between 7 and 4 (since there could be restriction in frames generation for that area), but this is a debatable proposal, since some players prefer a larger lists, and some other - showing two status info boxes.

Nevertheless, I suggest opening a discussion topic first to find out, what are the perfect combinations of castle/hero lists and status bar sizes, so a contributor would now, what to implement later.
