### ISSUE TITLE
Scenario info window is too close to upper screen edge

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6202] opened 2022-11-17 13:27 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/202458472-98c514d9-601e-4666-a7b4-1b434f5c68a8.png)
I suppose, window shadow shouldn't be taken to consideration while aligning this window.

### Save file

None.

**Comment by 2201monesh** [comment] 2022-11-17 13:40
Hey @Branikolog can you please elaborate the issue or can tell more details about it.

**Comment by Branikolog** [comment] 2022-11-17 14:04
Hello, @2201monesh !
![Info window](https://user-images.githubusercontent.com/55348946/202466554-dc922746-43dd-4646-9419-00b878c1c785.png)
As you see on screenshot, the upper edge of info window touches edge of the screen, while bottom edge is about 10 pixels to bottom screen edge.
Info window should have same gaps between upper and bottom edges of the screen.

**Comment by loki1205** [comment] 2022-11-17 14:20
Hi, my name is Loknath Kumar Mishra, I would like to contribute. Can you please assign this to me?

**Comment by Branikolog** [comment] 2022-11-17 14:43
Hi, @loki1205 !
Sure.

**Comment by loki1205** [comment] 2022-11-17 18:11
Hi, I cannot reproduce the issue on my PC.
![Screenshot (364)](https://user-images.githubusercontent.com/87192195/202524522-81e35ce6-798c-4ee2-ad18-61e89892141c.png)

**Comment by Branikolog** [comment] 2022-11-17 19:51
Hi, @loki1205 !
Try to use 640x480 resolution.
Anyway, the window is shifted for all resolutions. It should be in the middle of the screen. Now it's shifted ~ 6 pixels to the upper screen edge.

**Comment by zenseii** [comment] 2022-11-18 23:19
Seems like they retracted their assignment.

**Closed** 2022-11-24 21:49 UTC
Labels: bug, good first issue, ui
