### ISSUE TITLE
Abandoned Mine, hero's experience after combat

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1277] opened 2020-08-19 12:06 UTC
In fheroes2, the hero does not gain experience after defeating the ghosts.
The victory window is not displayed.
Only the mine restoration window is displayed.

In the original game:

![Abandoned Mine, hero's experience after combat 01](https://user-images.githubusercontent.com/43583994/90632624-01cb7600-e225-11ea-86f5-f97405b1141b.png)

In fheroes2:

![Abandoned Mine, hero's experience after combat 02](https://user-images.githubusercontent.com/43583994/90632637-055efd00-e225-11ea-8159-61ef872a3ae8.png)

**Comment by Branikolog** [comment] 2020-08-19 16:04
Hmm... On sdl2 version I can't reproduce your issue.... After battle I can see both victory window and mine restoration window.

**Comment by LeHerosInconnu** [comment] 2020-08-19 17:44
Hello @Branikolog,

Version: fheroes2_windows_x64_SDL2
Here is the test scenario file:
[Abandoned mine no victory window.zip](https://github.com/ihhub/fheroes2/files/5098267/Abandoned.mine.no.victory.window.zip)

Attack the ghosts with the first hero.

I can reproduce the bug without a problem.
The window for choosing a secondary skill may occasionally appear, but the victory window is never displayed.

**Comment by Branikolog** [comment] 2020-08-19 18:16
Hmmm. That's strange...
I've loaded your map and can watch a victory window after defeating ghosts...

**Comment by LeHerosInconnu** [comment] 2020-08-19 18:50
@Branikolog.

Strange, I can reproduce the bug with any hero.

**Comment by LeHerosInconnu** [comment] 2020-08-27 17:22
@Branikolog.

I did a test again with the given scenario and another scenario and now the victory window is displayed.
Another one of those nasty bugs. :)

**Comment by Branikolog** [comment] 2020-08-28 08:20
So, can I close this issue then?

**Comment by LeHerosInconnu** [comment] 2020-08-28 09:02
@Branikolog.

The bug has appeared, but it certainly only appears under certain conditions that are currently unknown and therefore it is not easily reproducible.
At the same time, I was able to easily reproduce it several times, as long as the conditions for its triggering were met.
I don't know how you handle these kinds of situations.

**Comment by Branikolog** [comment] 2021-01-24 14:20
@LeHerosInconnu 
I still couldn't reproduce this bug.
Could you, please, check it occasionally? It could be fixed by one of our previous PR, if it actually was. ) I think, we can close it the nearest time..

**Comment by LeHerosInconnu** [comment] 2021-01-24 18:03
@Branikolog.

> @LeHerosInconnu
> I still couldn't reproduce this bug.
> Could you, please, check it occasionally? It could be fixed by one of our previous PR, if it actually was. ) I think, we can close it the nearest time..

I did a quick test, it seems to work fine.
I think we can close the issue.
It will always be possible to report the bug if it appears again. :)

**Closed** 2021-01-25 07:52 UTC
Labels: bug, question, ui
