### ISSUE TITLE
How to deal with sdl12-compat in Mac app bundle builds?

### ISSUE THREAD

**Issue by Kreeblah** [ihhub/fheroes2#6084] opened 2022-11-04 07:45 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

The macOS Homebrew project removed SDL 1.2 not too long ago in favor of sdl12-compat, which makes sense since it's actively maintained, and recommended as a drop-in replacement for software which uses SDL 1.2.  However, this introduces some unique challenges for SDL 1.2 projects which use dylibbundler, which I did when adding Mac app bundle support to this project in order to allow for distribution of the app bundle without requiring users have libraries installed in the same locations on their systems.

In particular, the sdl12-compat library is built rather strangely due to how it operates, and how it's built with some of the original SDL 1.2 header files.  The end result here is that it doesn't list the SDL 2.0 library as a dependency, so dylibbundler never bundles the SDL 2.0 library into the app bundle, and it fails to launch with an error saying that SDL 2.0 can't be found (as that library is a dependency; it's loaded via internal C code in the library rather than marking the SDL 2.0 library as a dependency and letting the OS load it).

So, the end result here is that if somebody tries to run an SDL 1.2 Mac app bundle build that was built with sdl12-compat instead of true SDL 1.2, the app bundle will fail to run, even though it will appear to build correctly.

What I'm hoping to do here is open some discussion around what would be the best way of resolving this with the fheroes2 project.  I've tried talking to the SDL folks, but it's gone nowhere, so while I have solutions myself, there doesn't appear to be an officially endorsed solution.

As I see it, there are really two options:
1. Hard fail on SDL 1.2 Mac app bundle builds if they have sdl12-compat instead of true SDL 1.2.  This would be the case for any SDL 1.2 library with a patch version of 50 or above (so, 1.2.50 or above).
2. Detect sdl12-compat and copy the SDL 2.0 library to the same location within the Mac app bundle as the rest of the libraries as a separate (non-dylibbundler) step.

Option 2 would be more user-friendly while also being very doable in CMake (I already have a working implementation in another project at https://github.com/Kreeblah/MazeOfGalious, which relies on getting the path to the SDL 2.0 library from a modified FindSDL2.cmake file at https://github.com/Kreeblah/MazeOfGalious/blob/main/cmake/FindSDL2.cmake), though the Makefile-based builds could be challenging.  I'm not sure how to get the SDL 1.2 patch version out of that process, or how to determine the path to the SDL 2.0 library on the filesystem there.

Would the maintainers here have any preferences on how to go about solving this?  I'm happy to start work on it, but I was hoping to get thoughts on it first.

### Save file

N/A

**Comment by oleg-derevenetz** [comment] 2022-11-04 10:59
Hi @Kreeblah I personally vote for the option 1. In general, no one should use the SDL1. It would be good to drop SDL1 support completely, some platforms (such as game consoles or Android) are supported only using SDL2.

**Comment by zenseii** [comment] 2022-11-04 13:11
I thought we were building SDL1 for Mac only because we want to check if it build, because Mac moved on from SDL1 a long time ago.

**Comment by oleg-derevenetz** [comment] 2022-11-04 13:13
@zenseii

> I thought we were building SDL1 for Mac only because we want to check if it build, because Mac moved on from SDL1 a long time ago.

Yes, this is the only reason to build the SDL1 version - to check if it build :) I don't see a real use of SDL1.

**Comment by Kreeblah** [comment] 2022-11-04 16:33
Well, if the preference is to drop SDL 1.2 support for Mac entirely regardless of patch version and make it an SDL 2-only target, that seems like an even better solution to me than either of the ones I proposed.  You're right, that sdl12-compat is a crutch, and there's little need for it in an application that natively supports SDL 2.

I should be able to get started working on a pull request in the next few days to do that.

**Comment by ihhub** [comment] 2022-11-05 04:15
We do not distribute SDL 1 bundle for macOS. SDL 1 works only on older macOS versions. The newer macOS OSes must use only SDL 2.

Therefore, there is no need to modify the project to support SDL 1 for the latest Homebrew changes.

**Comment by oleg-derevenetz** [comment] 2022-11-05 09:23
Hi @ihhub the problem is that Homebrew dropped the SDL1 package in principle, on all macOS versions supported by the Homebrew. They offer the `sdl12-compat` package instead, which is in fact wrapper to support ancient SDL1-only apps using SDL2 (so calls of functions from SDL1 are translated to calls of corresponding/similar functions from SDL2). This wrapper is incompatible with macOS packaging infrastructure, invalid packages without essential libraries are produced, so we need at least check that we are not building "SDL1 macOS package" with `sdl12-compat` and fail the build if necessary with the corresponding error to let the user know what the problem is. Otherwise it will just get "successfully built", but invalid package that will not work.

**Comment by ihhub** [comment] 2022-11-05 09:30
@oleg-derevenetz , in this case we can still build SDL 1 as a part of the pipeline but we won't officially support it anymore.

**Comment by oleg-derevenetz** [comment] 2022-11-05 10:52
@ihhub

> in this case we can still build SDL 1 as a part of the pipeline but we won't officially support it anymore.

So you suggest just to leave everything as is and silently produce an invalid bundle when app is being built with `sdl12-compat` when the `FHEROES2_MACOS_APP_BUNDLE` is set?

**Comment by ihhub** [comment] 2022-11-05 11:01
@Kreeblah , if SDL 1 is chosen to this build we can simply fail or do not allow this to be happen until someone fixes this. We do not need to spend time of fixing such case.

**Comment by ihhub** [comment] 2022-11-05 11:02
@Kreeblah , if you have time and willingness to fix it and if the fix is trivial please go ahead and create a pull request.

**Comment by oleg-derevenetz** [comment] 2022-11-05 11:03
@ihhub so in fact you vote for option 1 from the issue description too? :)

**Comment by ihhub** [comment] 2022-11-05 11:04
> @ihhub so in fact you vote for option 1 from the issue description too? :)

Yes :)

**Comment by ihhub** [comment] 2023-08-22 12:46
Hi @Kreeblah and @oleg-derevenetz , as I understood we don't need to do anything as we are going with option 1?

**Comment by oleg-derevenetz** [comment] 2023-08-22 14:19
Hi @ihhub I suppose we will eventually drop SDL1 support completely and therefore we will close this issue. Currently macOS bundle is built as part of our Pull Request workflow, but not as part of our Push workflow, and is it not published anywhere.

**Closed** 2023-08-24 01:18 UTC
Labels: bug, SDL1, deployment, macOS
