### ISSUE TITLE
Price of loyalty: final map AI - is still play-able?

### ISSUE THREAD

**Issue by johndc** [ihhub/fheroes2#3780] opened 2021-07-01 12:34 UTC
Hi,
(my first issue here)

The final map for Price of loyalty campaign seems easy at the start (green player), then challenging (yellow and purple), but impossible in the last stage (red player).

I'm not sure about the original HOMAM2 AI in this map, but here I've found 5 red cities with little armies, some (up to 4) red heroes will little armies and complete troops are amassed under one hero - currently having like 1800 bone dragons.

Is this intended behavior? Joining all troop under one hero makes sense, but it makes really unplayable for the standard player. It would take 100s of months to amass enough troops to challenge it  (I know spells like a mirror image, anti-magic, etc..)

Or did I miss some deadline to finish the map earlier and now there is no chance to stop red player?

**Comment by ihhub** [comment] 2021-07-01 14:18
Hi @johndc ,

It looks like AI becomes too smart in some cases :) Could you please provide us save file to see what's going on?

**Comment by johndc** [comment] 2021-07-01 14:47
Here is it.
[Good_1_0038.zip](https://github.com/ihhub/fheroes2/files/6749027/Good_1_0038.zip)

**Comment by ihhub** [comment] 2021-07-01 15:01
Hi @johndc , it's the map itself. AI at the start has 1570 Bone Dragons across all castles and heroes. The strategy for this: try to make AI run out of spell points and then attack. Also kill Ghosts at first as you have very weak to Ghosts army. After this slowing down Bone Dragons gives you an advantage for 1 turn where you can shoot hundreds of them.

Anyway, I'm closing this issue since this is not a bug of this project. If you could like to continue discussion and strategies about this game you can join our Discord server **[here](https://discord.gg/xF85vbZ)**. Have a good play time!

**Closed by ihhub** 2021-07-01 15:01 UTC
Labels: question
