### ISSUE TITLE
Oracle and thieves guild doesn't show full information

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1150] opened 2020-07-27 13:06 UTC
![Oracle](https://user-images.githubusercontent.com/55348946/88544884-c9b88500-d022-11ea-94e5-d8d66b3d64bc.jpg)
Player cannot discover stats, personality and best monster of enemies.

**Comment by ihhub** [comment] 2021-04-25 03:36
Closing this issue as duplicate of #1589.

**Closed by ihhub** 2021-04-25 03:36 UTC
Labels: bug, good first issue, ui
