### ISSUE TITLE
Please add Filtering algorithms

### ISSUE THREAD

**Issue by denierlexiese** [ihhub/fheroes2#5656] opened 2022-07-15 04:25 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Full list of filters: Bilinear, Bicubic, ScaleNx (x2, x3), Super Eagle (x2), 2xSal (x2), ScaleHQ (x2, x4), xBRz (x2, x3, x4, x5, x6). 

Please add these as a feature.

### Describe the possible solution

https://www.gog.com/forum/heroes_of_might_and_magic_series/graphic_gl_wrapper_for_all_heroes_heroes_of_might_and_magic_1_2_3_4_and_chronicles_for_better_wo/page1

Something like this perhaps?

### Additional info

Thank you . Thank you for all the hard work you do.

**Comment by ihhub** [comment] 2022-07-15 04:36
Closing it as a duplicate of #4946.

**Closed by ihhub** 2022-07-15 04:36 UTC
Labels: improvement

**Comment by denierlexiese** [comment] 2022-07-15 05:14
i read #4946. I don't understand the resolution - can you explain?  Is there an existing way to get an xBRZ filter enabled?

**Comment by ihhub** [comment] 2022-07-15 05:29
Adding filter to a pixel art game is not the greatest solution. First of all, you have to understand how they work and what's they are used for. If we are going to add them we need proper description of each filter, pros and cons, what problems they solve and etc. Blindly adding a huge pile of filters is not a user friendly approach.

Heroes 3 is not a pixel art game, their sprites come from 3D models. That's why all these filters exist to make the game little more blurry. What Heroes 3 mods have is based on a limitation of modding itself and people are used to have these half-baked solutions. fheroes2 is not a mod and we can add a proper well-defined and fastest solution to solve needed problems. So the question is do we really need these filters or we can use some other solution?

In the case of Heroes 2, filters won't work easily by obvious reasons. The game uses 8 bit palette 2 layer images, not a standard RGBA images. You have to adapt these filters to make it happen which also leads to a great performance drop. Secondly, an integer scaling is the best way to preserve the quality of pixel art keeping performance almost at the same level.

I hope it answers your question. Please feel free to ask anything🙂

**Comment by denierlexiese** [comment] 2022-07-15 07:11
> Adding filter to a pixel art game is not the greatest solution. First of all, you have to understand how they work and what's they are used for. If we are going to add them we need proper description of each filter, pros and cons, what problems they solve and etc. Blindly adding a huge pile of filters is not a user friendly approach.
> 
> Heroes 3 is not a pixel art game, their sprites come from 3D models. That's why all these filters exist to make the game little more blurry. What Heroes 3 mods have is based on a limitation of modding itself and people are used to have these half-baked solutions. fheroes2 is not a mod and we can add a proper well-defined and fastest solution to solve needed problems. So the question is do we really need these filters or we can use some other solution?
> 
> In the case of Heroes 2, filters won't work easily by obvious reasons. The game uses 8 bit palette 2 layer images, not a standard RGBA images. You have to adapt these filters to make it happen which also leads to a great performance drop. Secondly, an integer scaling is the best way to preserve the quality of pixel art keeping performance almost at the same level.
> 
> I hope it answers your question. Please feel free to ask anything🙂

@ihhub 
xBRZ looks great on HOMM2. I know because i have from Verok's custom DLL file and can run that side by side and compare on a different monitor with fheroes2. The text and graphics look sharper than fheroes2.   Some people won't like it because it spoils the pixel art in their mind - but i think the trade off is worth it for the clarity. fheroes2 has way too many quality of life improvements for me to ever go back - but i think if I'm reading #4946 correctly - some others would like this feature as well.  Some of us like a filter spread across the graphics of the game even if others think it's blasphemous.

**Comment by denierlexiese** [comment] 2022-07-15 07:23
i want to stress how amazing the work you guys done is. I can now play this on linux ( i spent 40 hours trying to get it run on linux through wine ) - the overwhelming quality of life features is unbelievable.   The buy creatures from well, the 1 click transfer hero armies - the multiplayer shared fog of war, the sharing resources between players.  It's all so amazing. i just wish is had xBRZ filtering.

**Comment by Branikolog** [comment] 2022-07-15 13:27
Hi, @denierlexiese 
It would be interesting to look at the direct comparison of original sprite and filtered.
Could you, please, paste here a sprite of some creature and map object from both the original and filtered graphics?
I'm agreed with @ihhub here: pixel art, made for a small 640x480 resolution is not the field, where filtering should be applied. Especially in terms of limited game palette. It leads to some sort of soft mishmash instead of the original art. It could be used as an optional style for original graphics, but this looks like a work to satisfy some individual preferences, like changing the whole game palette or adding some weird texture effects and which will not be acceptable for the majority of players.

**Comment by denierlexiese** [comment] 2022-07-15 18:35
![titleFiltered](https://user-images.githubusercontent.com/26914652/179289028-238ae2b8-ef1d-4ee1-afb4-839bd6b6a8ce.PNG)
![titleOriginal](https://user-images.githubusercontent.com/26914652/179289030-91dfd4ca-41c4-4836-9598-eded4f56008b.png)
![castle800x600Filtered](https://user-images.githubusercontent.com/26914652/179289034-6c747412-b055-48ef-94f4-bf2eed2ce11f.png)
![castle800x600Original](https://user-images.githubusercontent.com/26914652/179289038-26fae639-02e5-48be-b980-4ff2da0a7a15.png)
![castleFiltered](https://user-images.githubusercontent.com/26914652/179289040-568606b0-caad-4e05-bb8e-473e2c6dff74.png)
![castleOriginal](https://user-images.githubusercontent.com/26914652/179289042-13c47099-7900-4243-b07e-fe8656f9870a.png)
![gameSettingsFiltered](https://user-images.githubusercontent.com/26914652/179289045-cc51347d-8fce-43a6-83bd-70136c48c7d2.PNG)
![gameSettingsOriginal](https://user-images.githubusercontent.com/26914652/179289048-6602f020-8fb5-47a2-9b61-bc68de7f059b.png)
![mapFiltered](https://user-images.githubusercontent.com/26914652/179289051-0f3002e8-71c9-48f9-9312-2c039bc8d1ca.png)
![mapOriginal](https://user-images.githubusercontent.com/26914652/179289055-b3db9748-e1ef-4e15-be4c-97b6dc2b92ed.png)
