### ISSUE TITLE
Add Full Controller Support

### ISSUE THREAD

**Issue by BTr-RJ** [ihhub/fheroes2#8592] opened 2024-04-26 14:15 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Please add full controller support (xinput and dinput) mainly for Linux.
I'm playing the GoG version in DosBox Pure and it works very well with a controller, If you could follow the same configuration pattern, that would be great.

### Describe the possible solution

Full controller support configuration gui

**Comment by ihhub** [comment] 2024-04-30 03:25
Duplicate of #4435

**Closed by ihhub** 2024-04-30 03:25 UTC
Labels: improvement
