### ISSUE TITLE
Adventure map: computer runs near me with weak army, he can see no danger

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#8208] opened 2023-12-29 11:03 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Computer runs near me with weak army, like there is no danger and I will not kill him in the next turn. So his turn is useless and actually he helps me to kill him (I don't need to catch him).
He could sit and defence in castle, then may be he could kill 1 my dragon, but he decides to do some kind of suicide, because I kill him with no loss.
Video: 

https://github.com/ihhub/fheroes2/assets/145407420/15ee8c15-4e64-4de0-899b-adbdf3ea713b

### Describe the possible solution

Computer should be afraid of strong army and if he sees one, he will need to go to castle to accumulate army or go to some corner of the map, where he can't be killed. May be pick some recources to get more army etc.

### Additional info

Version: 1.0.11
save: 
[blue suicide.zip](https://github.com/ihhub/fheroes2/files/13792789/blue.suicide.zip)

**Comment by ihhub** [comment] 2023-12-29 11:05
Closing as duplicate of #6259.

**Closed by ihhub** 2023-12-29 11:05 UTC
Labels: improvement
