### ISSUE TITLE
Windows 11: Graphics reverted to OG

### ISSUE THREAD

**Issue by SteLitY** [ihhub/fheroes2#5058] opened 2022-02-27 02:56 UTC
I updated to windows 11. The old version that I downloaded a year ago worked great. However, when I updated to the latest patch, it shows the older graphics. Everything looks grainy again
![a](https://user-images.githubusercontent.com/32561475/155866298-ec17f69f-b8c6-422a-b016-7c08cca673e9.png)
.

**Comment by ihhub** [comment] 2022-02-27 15:15
Hi @SteLitY , what version of the game do you use? Is it GoG or Gold? It looks like the loaded palette is incorrect.

**Comment by SteLitY** [comment] 2022-02-27 18:13
GoG

**Comment by ihhub** [comment] 2022-03-03 12:44
I haven't seen such graphics on any of machines. What exact version are you using? Can you provide a screenshot of a higher resolution set in the game?

**Comment by SteLitY** [comment] 2022-03-03 16:10
Whatever was the latest version on github 5 days ago is what I am using. According to the change log, it's: version 0.9.12 (07 February 2022)
Here are two screenshots:
![1](https://user-images.githubusercontent.com/32561475/156604312-68d1e5f3-39ad-48af-83c9-46a5bd297c5a.png)
![2](https://user-images.githubusercontent.com/32561475/156604321-2eb083e6-3932-4d6e-8593-909de7e0bcfc.png)

**Comment by ihhub** [comment] 2022-03-09 13:17
Hi @SteLitY , can you please try older than 0.9.12 version and find the one which has the correct graphics? It will help us to find the root of the problem?

**Comment by SteLitY** [comment] 2022-03-09 23:04
I can definitely do that, but do you know where I can find the older versions?

**Comment by ihhub** [comment] 2022-03-10 00:52
Hi @SteLitY , (here)[https://github.com/ihhub/fheroes2/releases] you can fine every release.

**Comment by SteLitY** [comment] 2022-03-10 03:42
After trying it out, it seems like the x86 or x64 SD1 for windows works fine, but the SD2 doesn't work. I'm using ryzen 5600x so I thought I would download the 64 bit version, but seems like I was wrong.

**Comment by ihhub** [comment] 2022-03-13 03:26
I think the problem might be in a driver which is used for image rendering.

**Comment by ihhub** [comment] 2022-04-03 13:06
Hi @SteLitY , we still to know which version broke the graphics. Could you please test every version starting from 0.9.12 till 0.9 to find out the one which breaks?

**Comment by ihhub** [comment] 2022-12-09 04:40
I believe the problem is with fullscreen mode and cursor software rendering. If the later is enabled the grainy part won't appear.

I'm closing this issue until the author replies back about trying software cursor rendering option on.

**Closed by ihhub** 2022-12-09 04:40 UTC
Labels: bug, SDL 2, ui, awaiting feedback
