### ISSUE TITLE
Neutral troops placed on a Water Lake upon a month of the monsters

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4388] opened 2021-10-11 14:47 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

The orc chiefs were placed on a Water Lake at the beginning of a month:
![Screenshot from 2021-10-11 16-43-17](https://user-images.githubusercontent.com/489601/136809959-d1755232-87f2-4e8c-864d-7646a4f29a47.png)

### Save file

[Wizard_0031.zip](https://github.com/ihhub/fheroes2/files/7323375/Wizard_0031.zip)

**Comment by ihhub** [comment] 2022-07-21 08:30
Duplicate of #4426.

**Closed by ihhub** 2022-07-21 08:30 UTC
Labels: bug, logic
