### ISSUE TITLE
ARM (Raspberry Pi4) build fails: link error undefined reference to `__atomic_load_8'

### ISSUE THREAD

**Issue by imiron13** [ihhub/fheroes2#5653] opened 2022-07-14 17:01 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

I tried to build the game (0.9.17) for Raspberry pi 4 (Raspberry Pi OS, Debian based) following the [this instruction](https://github.com/ihhub/fheroes2/blob/master/docs/DEVELOPMENT.md).
It fails on a linking stage with the following error:
```
/usr/bin/ld: ../engine/libengine.a(audio.o): in function `(anonymous namespace)::musicFinished()':
audio.cpp:(.text+0x160): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../engine/libengine.a(audio.o): in function `(anonymous namespace)::playMusic(unsigned long long, Music::PlaybackMode)':
audio.cpp:(.text+0x129c): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: audio.cpp:(.text+0x14c0): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: ../engine/libengine.a(audio.o): in function `(anonymous namespace)::MusicRestartManager::executeTask()':
audio.cpp:(.text+0x18dc): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../engine/libengine.a(audio.o): in function `Music::Stop()':
audio.cpp:(.text+0x2e64): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
```
Compiler: g++ (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110

I managed to finish the build by adding '-latomic' linker flag. I am not familiar with CMake so I just restarted linking with extra flag using a shell command.
Need to add this flag in the build system in order to support ARM/Raspberry Pi build.

See also:
https://github.com/ihhub/fheroes2/issues/4353

BTW, it works smoothly on Raspberry Pi 4. Haven't noticed any issues playing for ~30 mins. Quite enjoyable.

### Save file

N/A

**Comment by imiron13** [comment] 2022-07-14 17:08
> 

Thanks for the quick reply. Looks like the same issue this way..

**Comment by undef21** [comment] 2022-07-14 17:38
Hm, my RPi 1 build the game a little slower than you but building was successfull. Could you please do `make clean` before rebuild.

**Comment by oleg-derevenetz** [comment] 2022-07-14 19:31
I reclassified this as a request for improvement, because there are a 100500 different architectures, and we can't support everything. We reliably support only those architectures for which we build the binaries ourselves.

**Comment by undef21** [comment] 2022-07-20 19:43
I checked building on Debian 10 armel, armhf and arm64. This issue reproduced only on armel in my case. Looks like it's heavily depends on platform, gcc version and other factors, so I think it's the task for maintainers to add additional flags for a particular system.

**Comment by ihhub** [comment] 2022-07-21 00:53
We simply cannot and won't support many platforms as highlighted by @oleg-derevenetz . Our scope and possibilities are within GitHub actions and we cannot build any ARM stuff right now.

**Comment by Laserlicht** [comment] 2023-01-17 09:47
As a small addition: if you only want to play, then you can also take the flatpak version. I tested it yesterday on the Rasperry Pi. Runs without problems.

**Comment by ihhub** [comment] 2023-08-25 15:15
Closing this issue as this is beyond the scope of this project based on the discussion above.

**Closed by ihhub** 2023-08-25 15:15 UTC
Labels: improvement, help wanted, deployment, low priority
