### ISSUE TITLE
AI uses Summon Boat even though has two of them at his disposal and the stolen boat might be useful for his other hero

### ISSUE THREAD

**Issue by hatermeow2000** [ihhub/fheroes2#8504] opened 2024-03-20 17:35 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Android

### Describe the bug

Load this save. After hero in the south-east isle kills the player hero, he casts Summon Boat. This is excessive, as he already has 2 boats at his disposal, and the summoned boat might be useful to his other hero. At the very least, the boat is not in immediate danger of being immediately taken by other heroes as there is a castle and his other 2 heroes nearby.

### Save file

[saver.zip](https://github.com/ihhub/fheroes2/files/14670458/saver.zip)

**Comment by oleg-derevenetz** [comment] 2024-03-20 18:11
This is not a bug, that's how AI uses Summon Boat spell. In short, if AI has the Summon Boat spell (and reserve of mana), it paves the shortest path to the destination (including through the water) and calls the boat to the tile that is on this path. It will not make a detour for the sake of using an existing boat (even if this boat is located just one tile away from the paved path). When Mandigal gets into the boat, he is going to attack Ergon, so he needs to sail in a north-norttwest direction, so he summons the boat to the appropriate place.

**Comment by hatermeow2000** [comment] 2024-03-20 18:44
I dunno, maybe you are right. It's just that the AI behavior made me laugh when I had seen it and I thought that I should share this.

**Comment by ihhub** [comment] 2024-03-21 11:18
@hatermeow2000 , AI doesn't need to be like a human. If it's strategically better then AI would do. This is the case when summoning a boat gives an AI hero an advantage of paving the path.

**Comment by ihhub** [comment] 2024-04-13 04:57
I am closing this issue as it doesn't appear to be a bug but a desired behavior for AI projected from human player experience.

**Closed by ihhub** 2024-04-13 04:57 UTC
Labels: bug
