### ISSUE TITLE
Pop up info window's position in a world map while pointing a hero

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#730] opened 2020-06-04 21:39 UTC
While looking through hero statistics using right click you can notice, that pop up window appears at diferent positions in a case you move a bit mouse.
![Click](https://user-images.githubusercontent.com/55348946/83812898-ff955900-a6c4-11ea-8fa6-fbff920b5ee3.jpg)

**Comment by ihhub** [comment] 2020-06-14 03:54
This is not a bug as we divide a screen into 4 separate parts. The position of the window depends on which section (quadrant) you click. In this case the hero stands precisely in the middle of the screen. Please correct me if I am wrong otherwise we need to close the issue :)

**Comment by Branikolog** [comment] 2020-06-14 12:06
Currently pop up window of right click over any object on map is being shown on a certain distance from mouse cursor. But when you want to look at hero's info window - it is located in a fixed position to the hero, not to cursor. And when you move mouse a bit, window moves to the neighbor cell.(hero seems to cover more than one cell, that's why pop up window can appear in two places, if you move mouse over hero)

**Comment by ihhub** [comment] 2020-07-14 13:51
Putting this issue for 1.0 as there is action required for it.

**Comment by ihhub** [comment] 2022-11-26 11:14
Closing this issue as duplicate of #3666.

**Closed by ihhub** 2022-11-26 11:14 UTC
Labels: bug, help wanted, ui
