### ISSUE TITLE
Broken sound on android version 1.1.3

### ISSUE THREAD

**Issue by Mr-Bajs** [ihhub/fheroes2#9234] opened 2024-10-25 14:58 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Android

### Describe the bug

Opening the app and when the main menu starts there is no music just a hammering bashing repeating sound, same issue persists in games etx.

### Save file

.

### Additional info

OS: GrapheneOS 2024102400 (Android version 15)
Device Pixel tablet.
Datafiles from GOG.

**Comment by ihhub** [comment] 2024-10-25 15:04
Hi @Mr-Bajs , have you tried 1.1.2 version? Does it work properly?

**Comment by ihhub** [comment] 2024-10-25 15:05
It could be a regression from #9108 but it needs verification.

**Comment by oleg-derevenetz** [comment] 2024-10-25 15:30
For now, I was unable to reproduce this with the latest 1.1.3 from Google Play neither on my Android 14 phone, nor on my ancient Android 6 tablet. Here is the video from tablet, for instance:

https://github.com/user-attachments/assets/df20fad0-af80-4adf-b2d3-a4430670f9e1

Both External and MIDI music plays just fine.

**Comment by oleg-derevenetz** [comment] 2024-10-27 12:48
I don't have a "real" Android 15 device, but I just ran fheroes2 in the Android Studio emulator with Android 15 OS image and it seems that music and sounds generally work (this video was recorded by the emulator):

https://github.com/user-attachments/assets/8f042437-6ece-4a4b-b284-8dac798b9c79

There are some pops and clicks, but they may be related to some emulator "pecularities". At least there is nothing suspicious in the logs...

**Comment by ihhub** [comment] 2024-10-31 11:25
Hi @Mr-Bajs , can you please record the issue on your phone and attach here?

**Comment by miaw7** [comment] 2024-10-31 21:53
I have the same problem on my android 15, 1.1.3 game version 

Haven't played for a while, not sure on which version it was working fine last time 

Tried to record the video, but for some reason I can't capture the sound in the game

**Comment by oleg-derevenetz** [comment] 2024-10-31 22:17
Looks like this SDL issue:

https://github.com/libsdl-org/SDL/issues/11376

It has been fixed for SDL2 recently, let's wait for a new version.

**Comment by oleg-derevenetz** [comment] 2024-11-02 12:13
Hi @Mr-Bajs @miaw7 could you please try to install the APK from [here](https://github.com/ihhub/fheroes2/releases/tag/fheroes2-android) on your Android 15 devices to verify that audio issues are gone? Please note that you will need to uninstall the Google Play version first, because it is signed by a different certificate.

**Comment by Branikolog** [comment] 2024-11-02 12:15
Hi, @Mr-Bajs 
I also suggest moving save files into a separate folder as sometimes save files disappear during uninstall process.

**Comment by oleg-derevenetz** [comment] 2024-11-02 12:22
Hi @Branikolog

> I also suggest moving save files into a separate folder as sometimes save files disappear during uninstall process.

On Android, all files in the personal app data directory are automatically removed during app uninstallation process, but they can be _sometimes_ (not always) automatically restored from online backup when you install app once again (and online backups are created for fheroes2 save files and configs, but not for OG data files). So yes, it is better to export the save files before uninstalling the app using the fheroes2 Toolkit app.

**Comment by ihhub** [comment] 2024-11-03 07:18
Awesome! Closing this issue.

**Closed by ihhub** 2024-11-03 07:18 UTC
Labels: bug, audio, Android
