### ISSUE TITLE
Adventure map, horizontal position of the boat's sprite facing west is changed when a hero is boarding

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2180] opened 2020-11-06 20:36 UTC
In fheroes2, when the front of the boat is facing west and a hero is boarding, the horizontal position of the boat's sprite is changed.

In fheroes2:

![Boat position embark fh2 01](https://user-images.githubusercontent.com/43583994/98412201-d3b53f80-2077-11eb-8cd3-c9ce6ab88252.png)

![Boat position embark fh2 02](https://user-images.githubusercontent.com/43583994/98412178-c8faaa80-2077-11eb-8fa2-becd0e81444f.png)

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.

![Boat position embark fh2 coupé 01](https://user-images.githubusercontent.com/43583994/98412227-dd3ea780-2077-11eb-8456-70b3f2964887.png) ![Boat position embark fh2 coupé 02](https://user-images.githubusercontent.com/43583994/98412244-e465b580-2077-11eb-9cd9-811db1304b64.png)

Here is a video that show the bug encountered:
[Boat position embark fh2 01.zip](https://github.com/ihhub/fheroes2/files/5503405/Boat.position.embark.fh2.01.zip)

**Comment by ihhub** [comment] 2021-06-03 14:22
Closing as duplicate of #3243.

**Closed by ihhub** 2021-06-03 14:22 UTC
Labels: bug, help wanted, ui
