### ISSUE TITLE
No sounds when music is off even when sounds are not

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#237] opened 2019-11-20 12:54 UTC
Set music level to off in settings and notice that no sounds are available after.
![image](https://user-images.githubusercontent.com/19829520/69240516-9db54c00-0bd7-11ea-9696-842e515d45d2.png)

**Comment by andrey-starodubtsev** [comment] 2019-11-21 09:19
Cannot reproduce the issue on SDL2 Linux build.

Could you elaborate on your reproduction steps? Which system the problem is manifested on?

**Comment by ihhub** [comment] 2019-11-21 10:02
It's reproducible on Windows. Open the game change music to 0/off state and hear no sounds for hero movement nor surrounding objects.

**Comment by andrey-starodubtsev** [comment] 2019-11-21 11:43
Year, it's reproducible on Windows for me too; looks like the difference between platforms.

Will look closer at it.

**Comment by idshibanov** [comment] 2020-06-03 04:26
This looks like a bug in mixer's `Mix_VolumeMusic` call. It changes volume for all channels, not just music.

**Comment by idshibanov** [comment] 2020-06-28 16:00
Explanation of the identical problem, looks like it lies in Microsoft MIDI synth: https://github.com/WohlSoft/SDL-Mixer-X/issues/7

By the way I can reproduce this on SDL1 as well.

**Comment by idshibanov** [comment] 2020-07-20 03:56
@ihhub this is a well-known (for years!) Windows bug that won't be fixed. Only workaround I know is to use a custom MIDI player, something we won't do in the near future. I suggest to move this to 1.0.

**Comment by Branikolog** [comment] 2020-07-20 05:04
Can we do an infinitely low music level? (not switching off, but extremely quiet) 
Or can we try to play music in antiphase, to make it unhearable?

**Comment by idshibanov** [comment] 2020-07-21 04:02
> 
> Can we do an infinitely low music level? (not switching off, but extremely quiet)
> Or can we try to play music in antiphase, to make it unhearable?

The issue is that adjusting music volume changes volume for the whole application on Windows. Volume there acts as a master level. 

The only trick I see working if we don't adjust music volume at all (only MIDI and only Windows?) and just turn it off/on. It's up to debate if this hack is user-friendly and worth doing.

**Closed** 2022-07-23 04:49 UTC
Labels: bug, Windows, audio
