### ISSUE TITLE
unneccessary button in new game menu

### ISSUE THREAD

**Issue by senneschall** [ihhub/fheroes2#3116] opened 2021-04-07 06:28 UTC
When you open the new menu there is a button that has a totally messed up description. Clicking on it has the same effect as clicking on the "multiplayer" button:
![fheroes092newgamemenubug](https://user-images.githubusercontent.com/14364389/113820044-7d5d4180-977a-11eb-96b6-60ff5e0169a5.jpg)

fheroes 0.9.2 ubuntu_sdl2 version; game assets from the german gog dos version

**Comment by oleg-derevenetz** [comment] 2021-04-07 10:04
Hi @senneschall This button is the "Battle only" button that starts a sort of "deathmatch" - no global map, just a battle with chosen armies:

<img width="638" alt="Battle Only Start" src="https://user-images.githubusercontent.com/32623900/113848814-857ca780-97a1-11eb-944f-cdc35c729590.png">
<img width="640" alt="Battle Only Battle" src="https://user-images.githubusercontent.com/32623900/113848858-91686980-97a1-11eb-932c-11e505ff40e4.png">

Why its description is messed up in German language is another question...

**Comment by Branikolog** [comment] 2021-04-07 10:11
Hi, @oleg-derevenetz and @senneschall 

This is not original button. It was generated using native original english version. The reason of this issue is german version itself.  :)
I suppose, this would happen for every vesrion with not the same to english OG font.

**Comment by senneschall** [comment] 2021-04-07 12:06
I see, thanks :)
I was mislead because when I click the button, it opens a menu with only one button called "hot seat" - exactly the same as when I click the multiplayer button.

But when I use this button, the deathmatch battle starts. I should have tested this. So it's only the text that is messed up both in the shown above and the next menu.

Can I help you debug this, like providing a specific german file or so?

**Comment by oleg-derevenetz** [comment] 2021-04-07 12:30
> I was mislead because when I click the button, it opens a menu with only one button called "hot seat" - exactly the same as when I click the multiplayer button.

That's because it's actually multiplayer, but in the "battle only" mode :)

> Can I help you debug this, like providing a specific german file or so?

I can't say that yet, sorry :( I need to figure out first how those generated buttons work. Maybe the person who made them will be able to deal with the problem faster...

**Comment by ihhub** [comment] 2021-04-07 13:54
Hi @senneschall , we generate this button from a set of other buttons by using our engine capabilities. You can check `agg_image.cpp` file, **lines 136-157**. This works only for English version.

**Comment by ihhub** [comment] 2021-04-07 13:54
I'm moving this issue to 1.0 as we do not plan to support other languages in the nearest releases.

**Comment by Laserlicht** [comment] 2022-01-21 23:50
Is there anything new? More languages are now supported. Here is still missing a possibility for multi-language.

**Comment by ihhub** [comment] 2022-01-22 01:47
@Laserlicht , would you like to fix this issue?

**Comment by Laserlicht** [comment] 2022-01-22 13:06
@ihhub:

Possibly. But I haven't quite figured it out yet.

Do I understand correctly that the characters are again in a different font size and therefore you do not simply render a text?

It would also be impractical if you had to rebuild the button for each language.

Shouldn't we perhaps even deviate from the original and render all buttons with the BIGFONT?

https://github.com/ihhub/fheroes2/blob/3f031c86953d375bc47f13fd1a13b39806dbefd8/src/fheroes2/agg/agg_image.cpp#L1417

**Comment by ihhub** [comment] 2022-01-23 07:18
Buttons have their own font so big font won't help in this case. The problem is how to generate such font and we can't distribute letters as it's against licensing.

**Closed** 2022-04-02 17:19 UTC
Labels: bug, ui
