### ISSUE TITLE
Trolls in sailor campaign are immortal

### ISSUE THREAD

**Issue by motyl8891** [ihhub/fheroes2#8073] opened 2023-11-24 21:50 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

I started sailor campaign and it is not possible to loose because trolls are not loosing hit points

### Save file

No file

**Comment by oleg-derevenetz** [comment] 2023-11-24 22:09
If troll has not been killed during the battle turn, he restores full hitpoints at the beginning of the next turn, this is by design.

**Comment by ihhub** [comment] 2023-11-25 01:05
Closing this issue as Trolls have regeneration ability as per game design.

**Closed by ihhub** 2023-11-25 01:05 UTC
Labels: bug
