### ISSUE TITLE
(Android) 1.0.4 crashes at start. 1.0.3 works fine.

### ISSUE THREAD

**Issue by raidoraido** [ihhub/fheroes2#7187] opened 2023-05-15 14:09 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Android

### Describe the bug

(Android) 1.0.4 crashes at start. 1.0.3 works fine. Xperia T2 Ultra (Android 5.1.1).

### Save file

Just crashes on start.

**Comment by oleg-derevenetz** [comment] 2023-05-15 14:27
Duplicate of #7174.

**Comment by raidoraido** [comment] 2023-05-15 15:21
Mea culpa - i thought the reason was with game apk only and is not so global.

**Comment by oleg-derevenetz** [comment] 2023-05-15 15:27
> Mea culpa - i thought the reason was with game apk only and is not so global.

You can try to install the [latest snaphot](https://github.com/ihhub/fheroes2/releases/tag/fheroes2-android). Please note however that you will need to uninstall the current version if it was installed from Google Play (because version from Google Play is signed by a different certificate). But if you installed the current version from GitHub Releases section, you will be able to install the latest snapshot on top of the current version without the deinstallation.

**Comment by oleg-derevenetz** [comment] 2023-05-15 16:35
> This build works fine. No problems with res extraction and game apk.

Well, that's funny. It seems that NIO desugaring/emulation for older devices works just fine on debug builds, but not on release builds. Probably the optimizer somehow breaks the desugaring (throws away something necessary for work?)...

**Comment by admmlk** [comment] 2023-05-15 17:30
Hey, I also was able to successfully run the game on my Kiano Slimtab with Android 5.1.1 using that debug build while the official 1.0.4 and the snapshot mentioned earlier were failing.
Thanks a lot for quick reaction!

**Comment by oleg-derevenetz** [comment] 2023-05-16 09:16
Google raised the priority of my issue to P1 (only priority P0 is higher than this), so there is hope for a relatively quick fix.

**Closed** 2023-05-22 11:41 UTC
Labels: bug, Android

**Comment by oleg-derevenetz** [comment] 2023-05-22 12:17
Hi @raidoraido could you please test the release build from the [latest snapshot](https://github.com/ihhub/fheroes2/releases/tag/fheroes2-android) to ensure that now everything works in release builds too? Please check the operation of extracting assets from the archive of the original game, the operation of the game itself and the operation of the save file manager (reading the list of save files and deleting them).

**Comment by raidoraido** [comment] 2023-05-22 13:28
Hi, @oleg-derevenetz . 
1) Extracting assets works fine.
2) Operation of the game seems ok.
3) Savefile manager seems working fine too - saves ok, loads ok, rewrites ok. Dunno how to check deleting.

At quick view there is no problems.

Thanks a lot for you support and responsiveness.

**Comment by raidoraido** [comment] 2023-05-22 13:33
> there is also save file manager in the Toolset which allows to browse and delete save files. Does it also work?

Found it. Works ok - no problem with deleting savefile..

**Comment by oleg-derevenetz** [comment] 2023-05-22 14:09
@raidoraido thank you! :)

**Comment by admmlk** [comment] 2023-05-23 06:58
With that recent snapshot build, I also was able to run the game successfully.
Game runs smooth now (no debug build) and also looks beautiful in widescreen 768x480 resolution 💗!
I had no issues with extracting game resources and Save management tool also works correct.

@oleg-derevenetz Thank you and the entire team for great work 🎉
