### ISSUE TITLE
Add "Battle Only" button for Polush version of the game

### ISSUE THREAD

**Issue by J013k** [ihhub/fheroes2#5114] opened 2022-03-12 16:09 UTC
### Your question

Hi!

Is there a chance to replace a strange entry in the main menu with the one from an original EN version?

Or translate it:
Battle Only -> Tylko Bitwa

### Additional info

Here is how it looks like in PL version:
![https://i.postimg.cc/R0c57xCK/rre-1.png](https://i.postimg.cc/R0c57xCK/rre-1.png)
Standard Game -> Gra Standardowa
Campaign Game -> Kampania
Multi-Player Game -> Gra Dla Wielu Osób
**Battle Only -> ?**
Config -> Konfiguracja
Cancel -> Anuluj

Here is how it looks like in EN version:
![https://i.postimg.cc/fT0HtjR0/fheroes2-menu.png](https://i.postimg.cc/fT0HtjR0/fheroes2-menu.png)

**Comment by oleg-derevenetz** [comment] 2022-03-12 16:47
Duplicate of #3116

**Comment by J013k** [comment] 2022-03-12 18:29
Thank you!

There is no need to duplicate the same issue.

**Comment by Laserlicht** [comment] 2022-04-03 12:30
With #3116 only the german version is fixed.

https://github.com/ihhub/fheroes2/pull/4951 has to be done for PL (and other languages) as well.

**Comment by zenseii** [comment] 2022-04-03 12:34
I'll have a look at doing this for at least Italian and Norwegian after my current work regarding those languages is finished.

**Closed** 2022-04-09 06:10 UTC
Labels: question, ui
