### ISSUE TITLE
AI players sits in town for no reason

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#7774] opened 2023-09-19 00:57 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

AI player (orange) sits in his town for no reason. He had enought movement points to pick up the chest and go back sit in town (I also started game for orange knight, movement points are enough to pick up chest and go back).
![pickupchest](https://github.com/ihhub/fheroes2/assets/145407420/35de1694-74d8-4a7b-9572-02f4fc9cdfb9)

https://github.com/ihhub/fheroes2/assets/145407420/9bc49026-4af8-42c2-9591-7227b0d5b5e3

[orange player ignores chest.zip](https://github.com/ihhub/fheroes2/files/12654516/orange.player.ignores.chest.zip)

### Describe the possible solution

If AI is planning just to sit in town, he could pick something useful, if it is not ruining his plan and he can be back in town in the end of the day.

**Comment by ihhub** [comment] 2023-09-19 01:09
Duplicate of #7346

**Closed by ihhub** 2023-09-19 01:09 UTC
Labels: improvement
