### ISSUE TITLE
Cannot close game while battle in castle

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#649] opened 2020-05-26 13:52 UTC
While defending a castle player cannot cancel fight: our version accepts only retreat from the battle, but player cannot retreat from a castle.

**Comment by Branikolog** [comment] 2020-05-26 15:39
Actually game has no reaction on trying to close it by Alt+F4 or trying to close it in window mode with the help of [X].

**Comment by Branikolog** [comment] 2020-07-30 11:28
Currently, the game can be closed only on a world map. When player is in battle, or in castle or other info window game has no reaction on your tries to close it.

**Comment by ihhub** [comment] 2022-06-19 13:45
Closing this issue as a duplicate of #3042 .

**Closed by ihhub** 2022-06-19 13:45 UTC
Labels: help wanted, ui
