### ISSUE TITLE
Original campaign mission 2 - can't move hero 

### ISSUE THREAD

**Issue by enk37** [ihhub/fheroes2#3829] opened 2021-07-11 12:00 UTC
There is some strange issue with original campaign mission 2. Hero can't move more than 2 steps away from castle, e.g you can't pickup gold or mercury on the road, looks like road is blocked. Not sure why it is so. See attached screenshots. This is 0.9.5 version  running on MacOS bigSur.
<img width="1680" alt="Screenshot 2021-07-11 at 14 57 47" src="https://user-images.githubusercontent.com/28488706/125194128-a77e3e00-e258-11eb-91da-b65e68cf86af.png">
<img width="1680" alt="Screenshot 2021-07-11 at 14 57 53" src="https://user-images.githubusercontent.com/28488706/125194124-9fbe9980-e258-11eb-888f-79005e12c619.png">

**Comment by oleg-derevenetz** [comment] 2021-07-11 12:14
Duplicate of #3814

**Comment by ihhub** [comment] 2021-07-11 12:20
Hi @enk37 , please take a look at #3814 . It's fixed and you can download a version with the fix. Please read the last message there.

**Closed by ihhub** 2021-07-11 12:20 UTC
Labels: bug, logic
