### ISSUE TITLE
libsmacker::smk_read_file(buf,3,fp) - ERROR: Short read, 0 bytes returned Reason: Not a directory

### ISSUE THREAD

**Issue by elias137** [ihhub/fheroes2#6614] opened 2023-02-12 19:08 UTC
### Your question

While trying to run on Ubuntu 22.04 game quits with the next error:

./fheroes2 
fheroes2 engine, version: 1.0.1
libsmacker::smk_read_file(buf,3,fp) - ERROR: Short read, 0 bytes returned
	Reason: Not a directory
libsmacker::smk_read(...) - Errors encountered on read, bailing out (file: smacker.c, line: 692)
fheroes2: smacker.c:862: smk_open_generic: Assertion `hufftree_chunk' failed.
Aborted (core dumped)

Is this a bug or do I have to install some library to make fheroes work?

**Comment by oleg-derevenetz** [comment] 2023-02-12 19:11
> Is this a bug or do I have to install some library to make fheroes work?

It looks like your game assets have some invalid SMK files (probably zero size?). Where did you get these assets?

**Comment by elias137** [comment] 2023-02-12 19:13
I've downloaded it somewhere on the Internet

**Comment by oleg-derevenetz** [comment] 2023-02-12 19:14
> I've downloaded it somewhere on the Internet

Well, you need a proper assets.

**Comment by ihhub** [comment] 2023-02-13 15:30
I am closing it as a duplicate of #5741.

**Closed by ihhub** 2023-02-13 15:30 UTC
Labels: question
