### ISSUE TITLE
fheroes2 does not run on 32-bit Win XP

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5327] opened 2022-04-23 16:40 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

A user Denise on Discord reported that fheroes2 does not run on their 32-bit Windows XP with latest official updates to the OS (from 2020).

![20220421_174612](https://user-images.githubusercontent.com/12501091/164914978-e6174c29-118c-4600-97ad-a3eefcae383b.jpg)

They tested latest snapshots of x86 SDL1 and SDL2 .zip builds and had fheroes2 installed in a directory separate from original Heroes 2 files.

I've successfully tested fheroes2 on Win 7 32-bit.

They tested on two PCs:
Asus PC Eee 4g
and
"PC built partially myself with Pentium 4 CPU, 1.5gb DDR1 RAM, Radeon 9600xt 128mb video RAM".

### Save file

Setup specific.

**Comment by Alucard648** [comment] 2022-04-23 16:41
WinXP support was dropped long ago.

**Comment by zenseii** [comment] 2022-04-23 16:48
> WinXP support was dropped long ago.

I see, I did not know this and I can't find any reference to it other than this post where it seems to still be supported?https://github.com/ihhub/fheroes2/pull/3455#discussion_r635093271

I also wonder what systems are supported that only support SDL1 at this point are?
@oleg-derevenetz would you have time to give a comment on this issue in case you know anything about it?

**Comment by oleg-derevenetz** [comment] 2022-04-23 17:08
Hi @zenseii Visual Studio 2019 (which is used by our auto-build machinery) is not able to build apps for Windows XP anymore. But he can try to build the project himself with C++ compiler from VS2017 [using this guide](https://docs.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=msvc-170).

**Comment by Gerwin2k** [comment] 2022-04-23 18:11
Actually "fheroes2_windows_x86_SDL2" works on windows XP, it is just that the MSVC compiler puts in bits that say it should check for NT version 6. In the attached image you can see the two occurrences of NT version "06" in yellow. Make these both "05" with a hex editor and the game runs fine after that. 
![fheroes2_nt-version](https://user-images.githubusercontent.com/39087372/164934233-e3c53e8e-587b-447c-8a24-85f0f9f3eabc.png)

Though, if the devs should do something like this: 
```
drop XP support from settings file
"cmake.generator": "Visual Studio 16 2019",
- "cmake.toolset": "v141_xp",
+ "cmake.toolset": "v142",
```
Then it will become much harder, sometimes KernelEX dll's can still make it work...

I found fheroes2 sourcecode can be compiled on Windows XP for Windows XP with GCC 8.4.

**Comment by oleg-derevenetz** [comment] 2022-04-23 18:24
@Gerwin2k I don't see a point to build it for WinXP (why not Win2000 or Windows 95?). Those who wish can do it themselves using VS2017 or earlier.

**Comment by Gerwin2k** [comment] 2022-04-23 18:31
Are you misunderstanding my message?
I was not suggesting the fheroes2 Developers should do anything different. 
I suggested some alternate things that the topic started can do to make it work on XP, by themselves, for themselves. And my first suggestion is simple+quick compared to obtaining, installing and setting up VS2017.

**Comment by zenseii** [comment] 2022-04-23 19:02
> Actually "fheroes2_windows_x86_SDL2" works on windows XP, it is just that the MSVC compiler puts in bits that say it should check for NT version 6. In the attached image you can see the two occurrences of NT version "06" in yellow. Make these both "05" with a hex editor and the game runs fine after that. ![fheroes2_nt-version](https://user-images.githubusercontent.com/39087372/164934233-e3c53e8e-587b-447c-8a24-85f0f9f3eabc.png)
> 
> Though, if the devs should do something like this:
> 
> ```
> drop XP support from settings file
> "cmake.generator": "Visual Studio 16 2019",
> - "cmake.toolset": "v141_xp",
> + "cmake.toolset": "v142",
> ```
> 
> Then it will become much harder, sometimes KernelEX dll's can still make it work...
> 
> I found fheroes2 sourcecode can be compiled on Windows XP for Windows XP with GCC 8.4.

Thanks you for sharing this simple solution @Gerwin2k . I'll forward your message, and we can close this issue since Windows XP is obviously not supported and will not be in the future.

**Comment by oleg-derevenetz** [comment] 2022-04-23 19:14
@Gerwin2k

> I suggested some alternate things that the topic starter can do to make it work on XP, by themselves, for themselves. And my first suggestion is simple+quick compared to obtaining, installing and setting up VS2017.

This EXE patching may work at first sight, but it may lead to issues later, because VS2019 runtime with which the application is currently built may use some syscalls that just absent in WinXP (especially related to threads), so the app may crash at the worst possible moment. This is not the recommended way to run the app on WinXP.

**Comment by Gerwin2k** [comment] 2022-04-23 19:29
Well, I think "VS2019 v141_xp" toolset is just bugged in that it makes XP compatible executables, but writes NT6 in the PE header anyways. 

Though "VS2019 v142" toolset is a different matter, and allows for NT6 API calls. 

I have done PE header hexedit many times with "VS2019 v141_xp" based builds of all kinds, and had no issues with it. 

Though if there is indeed even a single DLL/API call that is unrecognized, or unhandled, Windows will throw a fatal error message at a very early stage, during the DLL/API check.  E.g. You cannot even execute it in that case. It will just refuse.

**Comment by ihhub** [comment] 2022-05-01 09:23
We could revive AppVeyor which was compiling the engine under VS 2015 but is it worth the efforts?

**Comment by ihhub** [comment] 2022-12-09 04:36
Closing this issue as a duplicate of #6002

**Closed by ihhub** 2022-12-09 04:36 UTC
Labels: improvement, Windows, low priority
