### ISSUE TITLE
Window elements do not disappear instantly

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7664] opened 2023-08-29 21:04 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I've noticed several cases when button or the internal part of the window disappear before the rest window.

https://github.com/ihhub/fheroes2/assets/55348946/8ec1dcee-a3e3-4eb2-a6e7-209b1e9b0190

![image](https://github.com/ihhub/fheroes2/assets/55348946/0559442e-2b55-4b00-a270-e792de5450cf)
![image](https://github.com/ihhub/fheroes2/assets/55348946/a968fb6f-2ca5-4576-8eff-807bd2940a1d)

### Save file

None.

**Comment by ihhub** [comment] 2023-08-30 06:44
Closing as duplicate of #7281.

**Closed by ihhub** 2023-08-30 06:44 UTC
Labels: bug, ui
