### ISSUE TITLE
Scenario window, memorized scenario

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1253] opened 2020-08-16 12:29 UTC
In the original game, if you play a scenario with all hero classes in random mode for all players, and you choose the knight for the human player, and then you run the scenario, and decide to start that scenario over again, the human player's hero class is remembered and all other classes remain in random mode.

In fheroes2, if you do the same, the class of all heroes is remembered, forcing the user to put all classes of AI players back to random mode.
What a pain. :)

In the original game:

![Scenario window 07](https://user-images.githubusercontent.com/43583994/90334192-342e6680-dfcc-11ea-97e5-57281b838d38.png)

In fheroes2:

![Scenario window 08](https://user-images.githubusercontent.com/43583994/90334197-3bee0b00-dfcc-11ea-9a23-8af827fcfd90.png)

**Comment by Moiman** [comment] 2020-08-17 04:27
Duplicate of #265

**Comment by LeHerosInconnu** [comment] 2020-08-17 09:21
Hello @Moiman,

Effectively.
The search did not display this issue with the term "scenario", nor with the term "memorized", nor with the term "window".

**Comment by Branikolog** [comment] 2020-08-17 10:39
Hi, @LeHerosInconnu!
Don't bother.
Also, you can always ask me, if certain bug already exists in issue list.

**Closed by Branikolog** 2020-08-17 10:39 UTC

**Comment by LeHerosInconnu** [comment] 2020-08-17 11:09
Hello @Branikolog,

Yes thanks.
I'll see what I'll do.
There are so many bugs to report that it takes a long time to find out if they have already been reported. :)
