### ISSUE TITLE
Quiting in main menu doesn't close app in Android

### ISSUE THREAD

**Issue by Mr-Bajs** [ihhub/fheroes2#6449] opened 2023-01-02 17:41 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Android

### Describe the bug

When selecting Quit in the main menu, you only exit the app but it doesn't quit/kill the app. It stills runs in the background., You have to quit the app through the regular android swipe app quitting.
 

### Save file

.

### Additional info

Samsung Tablet A8 
Android 12
fheroes2 1.0.0

**Comment by oleg-derevenetz** [comment] 2023-01-02 18:00
Nope, it really *does* quit the app process, literally. It doesn't run in the background, it's just an app "card" shown you by a task manager. If you will run any other Android app and press the Android back button immediately, the effect will be the same - app "card" still will be shown to you by Android task manager for at least some time. How is this a bug?

**Comment by Mr-Bajs** [comment] 2023-01-02 19:19
Okey.

I would still argue it's a bug. But maybe an Android bug rather then fheroes2 bug. ;)

**Comment by oleg-derevenetz** [comment] 2023-01-02 19:30
> I would still argue it's a bug. But maybe an Android bug rather then fheroes2 bug. ;)

It's a "feature" of Android task manager - it still shows the apps that are already finished. IIRC this list of app cards is in fact called "Recents screen", which kind of hints that this is not a list of currently running applications, but a list of applications that have been **_recently accessed_** :) So it's not a bug, it's by design.

**Comment by oleg-derevenetz** [comment] 2023-01-07 00:03
I believe that we can close this issue, because in fact it is not an issue of any kind, but is caused by a misunderstanding of the principle of how the Recents screen works in Android.

**Closed** 2023-01-07 00:03 UTC
Labels: bug
