### ISSUE TITLE
Most recent snapshot: ART 2 on map has an icon and isn't remove after being taken

### ISSUE THREAD

**Issue by saox** [ihhub/fheroes2#3909] opened 2021-07-26 07:51 UTC
![art2](https://user-images.githubusercontent.com/3976222/126952149-115f4a52-2e18-441e-bbda-ced285731a46.png)

**Comment by oleg-derevenetz** [comment] 2021-07-26 09:09
Looks like a duplicate of #3764

**Closed** 2021-07-26 09:33 UTC
Labels: bug, ui
