### ISSUE TITLE
Alchemy lab rendering bug in camaping map

### ISSUE THREAD

**Issue by AAS** [ihhub/fheroes2#6857] opened 2023-03-18 03:14 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In "Voyage Home - Pirate Isles" there is alchemy lab in upper right corner of the map.
It rendered incorrectly in 1.0.2. Right clicking on it shows just "mine" text.

![image](https://user-images.githubusercontent.com/179733/226081387-398a7bac-b2cf-4520-a557-8fdaa3301ad3.png)

### Save file

[hidden_mine.zip](https://github.com/ihhub/fheroes2/files/11007350/hidden_mine.zip)

**Comment by oleg-derevenetz** [comment] 2023-03-18 04:55
Duplicate of #5537.

This is not fheroes2-related bug, this is a bug in the map editor from the original game. The same place in the original game:

![bug1](https://user-images.githubusercontent.com/32623900/226085473-de8bc04a-9a52-4b03-9c83-1fd7a0e1ed8b.jpg)
![bug2](https://user-images.githubusercontent.com/32623900/226085474-b5a144e3-3c87-48ef-9668-1fdd1b388b12.jpg)

As you can see, the situation is the same.

**Comment by ihhub** [comment] 2023-03-19 05:06
Closing this issue as duplicate.

**Closed by ihhub** 2023-03-19 05:06 UTC
Labels: bug
