### ISSUE TITLE
AI doesn't see partially unveiled castle.

### ISSUE THREAD

**Issue by kitovyj** [ihhub/fheroes2#9012] opened 2024-07-29 04:09 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

It seems that green AI doesn't consider partially unveiled red castle (the last one) as a target. Why?

### Save file

[ai does not see the castle.zip](https://github.com/user-attachments/files/16407325/ai.does.not.see.the.castle.zip)

**Comment by oleg-derevenetz** [comment] 2024-07-29 07:36
This is a duplicate of #7343 and it concerns not only castles, but any multi-tile objects whose "main" tile (i.e. action tile) is not visible to the AI yet.

**Comment by ihhub** [comment] 2024-07-29 23:46
Closing this issue as duplicate.

**Closed by ihhub** 2024-07-29 23:46 UTC
Labels: bug
