### ISSUE TITLE
Scenario window, information windows

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1251] opened 2020-08-16 12:22 UTC
This is valid for all the information windows of the scenario window.
- In fheroes2, the vertical position of the displayed window is not the same as in the original game.
- In fheroes2, the window is not centered horizontally with respect to the home screen.
In the original game, this window is centered horizontally with respect to the home screen.
- In fheroes2, the vertical position of the text in the info window is not the same as in the original game.
- In fheroes2, the text shadow is lighter than the text shadow in the original game.

In fheroes2, there is no information window for the double arrows which allow to change the order of play of the players.

I suggest all these windows to be centered both vertically and horizontally in fheroes2.
This taking into account only the rectangular part of the window graphic, in my opinion the upper and lower "decorations" of the window graphic should not be taken into account for the window centering.

In the original game:

![Scenario window 05](https://user-images.githubusercontent.com/43583994/90334110-6c817500-dfcb-11ea-9422-741629bda5c3.png)

In fheroes2:

![Scenario window 06](https://user-images.githubusercontent.com/43583994/90334115-74411980-dfcb-11ea-95c2-ac549f0bf27e.png)

**Comment by Branikolog** [comment] 2020-08-17 12:38
Duplicate of #1245 and #1167.

**Closed by Branikolog** 2020-08-17 12:38 UTC

**Comment by LeHerosInconnu** [comment] 2020-08-17 17:26
@Branikolog,

You told me to make separate topics for each issue, despite similar ones, here it is two different windows.
For my part, I would prefer to put all similar issues in a single topic, it would save me work.
So what's the best way to go?
