### ISSUE TITLE
Combat, AI does not optimize the placement of its troops against creatures that attack on two hexagons

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2729] opened 2021-02-03 16:38 UTC
In fheroes2, AI does not optimize the placement of its troops against creatures that attack on two hexagons.
In the example, the Skeleton troops move into adjacent hexagons favoring the attack of the Phoenixes the next turn, while there is room for the Skeleton troops to attack without moving into adjacent hexagons.

In fheroes2:

https://user-images.githubusercontent.com/43583994/106778474-4f5a6480-6646-11eb-8f0a-588a911c77ed.mp4

**Comment by ihhub** [comment] 2024-05-24 08:45
Closing it as duplicate of #7402.

**Closed by ihhub** 2024-05-24 08:45 UTC
Labels: improvement, AI
