### ISSUE TITLE
Translate all cyrilic to latin alphabet

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#8862] opened 2024-06-23 03:32 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

We have maps done in russian editor, by russian gamers:
![image](https://github.com/ihhub/fheroes2/assets/145407420/ac3d69aa-9fde-4456-bab5-8e25a4b4cde4)

But when playing an english version of the game, we see questions insted letters:
![image](https://github.com/ihhub/fheroes2/assets/145407420/7d70fba7-94d5-4315-9988-57e09c6db590)

### Save file

[russian.zip](https://github.com/user-attachments/files/15942406/russian.zip)

### Additional info

I can see 2 solutions:
1.Try fheroes2 to implement all the translation (for example, translate the map descriptions, sphinx questions, events on the map) so english-speaking users could understand it. May be, just include Russian–English vocabulary - that should be enough to understand the main meaning.
2. Just simply translate the letters to english, so Крэг Хэг - Crag Hack, захват - zahvat, капитуляция - capituliatzia. English-speaking gamer won't understand it, but russian (will english version of the game) - will understand.

**Comment by ihhub** [comment] 2024-06-23 04:24
This is not a bug and it is not doable at all. The original game was released in many languages and there is no way to identify which language a map uses. We had discussions in the past and no solution exists to even remotely solve the problem of identifying a language of the map.

**Closed by ihhub** 2024-06-23 04:24 UTC
Labels: bug
