### ISSUE TITLE
price of loyalty 8  last mission 

### ISSUE THREAD

**Issue by Olegarh1a** [ihhub/fheroes2#8729] opened 2024-05-24 05:49 UTC
### Your question

impossible the computer is gathering a very large army. Unable to complete mission. all computer players in the alliance are against you

**Comment by ihhub** [comment] 2024-05-24 05:51
@Olegarh1a , please reduce the difficulty of the campaign and replay the mission.

I am closing this issue as this is not a bug but a lack of experience of playing this game.

**Closed by ihhub** 2024-05-24 05:51 UTC
Labels: question

**Comment by Alucard648** [comment] 2024-05-25 04:32
Same issue. Normal difficulty. Keep getting rushed on week 5 with 3-4k skeletons, and other troops up to scale and huge stats. If i get unlucky, I got DD`ed on week 3 with 2-3k skeletons, 200 vampire lords and such. My main hero (no units lost at all) got 1-turn-wiped with single Chain Lightning or Elemental Storm spell. Or just Mass Slow and full-on rush.
