### ISSUE TITLE
Seven Lakes Map - Weed Patch Castle - Permanent "built state" bug.

### ISSUE THREAD

**Issue by gernstsmit** [ihhub/fheroes2#3713] opened 2021-06-19 07:04 UTC
The Weed Patch Castle icon has a permanent x marker on it. This marker normally indicates that something has been built today at the castle already and that you have to go to your next day to build something else. In this case the x marker does not disappear when you go to the next day.

**Comment by gernstsmit** [comment] 2021-06-19 07:08
Here is a screen shot were you can see the x on the castle icon to the right of the screen even though nothing has been built at that castle.

https://drive.google.com/file/d/1zIUTEWtnRAFbb4F6k7fUh_oILLeSRhKD/view?usp=sharing

**Comment by ihhub** [comment] 2021-06-19 07:10
Hi @gernstsmit , could you please provide a save file for replicate the issue?

**Comment by ihhub** [comment] 2021-07-02 14:38
This is not a bug. If a castle has nothing more to built it has such icon. Closing this issue.

**Closed by ihhub** 2021-07-02 14:38 UTC
Labels: awaiting feedback

**Comment by qarkai** [comment] 2021-07-02 15:27
It differs from OG behavior. Alteris2 map (from GOG Gold) has fully built castle from start and it's icon doesn't have 'x' marker. Although in fheroes2 it doesn't have too.
Upd. If you fully build another castle on the same map (warlock's, need only two days) it will have 'x' marker on it's icon in fheroes2, but not in OG.

**Comment by LeHerosInconnu** [comment] 2021-07-02 18:39
Hello everyone,

Yes, this is annoying and disturbing.
I have made a proposal to remedy this problem: https://github.com/ihhub/fheroes2/issues/1992.
