### ISSUE TITLE
improvements to the list of savegames dialog

### ISSUE THREAD

**Issue by jeanph01** [ihhub/fheroes2#9046] opened 2024-08-13 18:08 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

sometimes there's so much savegames that it get tedious to find the one we are looking for. The ability to order by date or name would be a first and then display the map name could be cool. 

### Describe the possible solution

rework the load game dialog

### Additional info

#improvement #ui

**Comment by oleg-derevenetz** [comment] 2024-08-13 19:02
> display the map name could be cool

The map name and the in-game date (month/week/day) are already displayed in the quick info window, which is shown when the right mouse button is pressed on the corresponding save file.

**Comment by TLCD17** [comment] 2024-08-13 20:46
I was going to write a similar topic, only with more details.
Specifically, in my opinion, the saves that a player creates in h2HD in campaigns and single missions should be sorted by: 1. Date, 2. Name and 3. Order.
This is because one player will create many saves in a month of one campaign and would like to quickly find the save file by name, while another will create only one or two saves for one mission or not save at all.
Moreover, if you save any save file from a campaign, mission (the newest), it should always be at the very top, not in the middle, as by date.
From what I know, saves are currently sorted by date.
I also want to mention that in none of the folders from fheroes2 there are any saves (files) of missions from campaigns (or more precisely the names of saves from individual campaigns or missions, which are only in saves available after opening the game).
Mission and campaign save files that the player would create in the fheroes2 folder would have the option to delete them en masse, rather than individually as via the save tables after opening the game).

**Comment by TLCD17** [comment] 2024-08-13 20:48
I was going to write a similar topic, only with more details.
Specifically, in my opinion, the saves that a player creates in h2HD in campaigns and single missions should be sorted by: 1. Date, 2. Name and 3. Order.
This is because one player will create many saves in a month of one campaign and would like to quickly find the save file by name, while another will create only one or two saves for one mission or not save at all.
Moreover, if you save any save file from a campaign, mission (the newest), it should always be at the very top, not in the middle, as by date.
From what I know, saves are currently sorted by date.
I also want to mention that in none of the folders from fheroes2 there are any saves (files) of missions from campaigns (or more precisely the names of saves from individual campaigns or missions, which are only in saves available after opening the game).
Mission and campaign save files that the player would create in the fheroes2 folder would have the option to delete them en masse, rather than individually as via the save tables after opening the game).

**Comment by oleg-derevenetz** [comment] 2024-08-13 22:29
> I also want to mention that in none of the folders from fheroes2 there are any saves (files) of missions from campaigns (or more precisely the names of saves from individual campaigns or missions, which are only in saves available after opening the game).

All save files are located in the user directory. On Windows they are stored in `%APPDATA%\fheroes2\files\save` directory, also there is a shortcut in the `fheroes2` folder in the Windows Start menu called "Game data files", which opens the `%APPDATA%\fheroes2` folder in the Windows Explorer.

> Mission and campaign save files that the player would create in the fheroes2 folder would have the option to delete them en masse

Just open the appropriate folder and do whatever you like with them.

**Comment by jeanph01** [comment] 2024-08-14 12:30
Hmm idea : then maybe add options in this “right click” dialog to sort the list ?

De : Oleg Derevenetz ***@***.***>
Envoyé : 13 août 2024 15:03
À : ihhub/fheroes2 ***@***.***>
Cc : Martin, Jean-Philippe ***@***.***>; Author ***@***.***>
Objet : Re: [ihhub/fheroes2] improvements to the list of savegames dialog (Issue #9046)

Vous ne recevez pas souvent de courriers de la part de ***@***.******@***.***>. Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>
ATTENTION ! CE COURRIEL PROVIENT DE L’EXTERNE
Avant d’ouvrir ou de télécharger une pièce jointe ou de cliquer sur un lien, assurez-vous que le courriel provient d’une personne ou une organisation de confiance.
Faites preuve de vigilance, développez les bons réflexes, et ne téléchargez aucune pièce jointe non sollicitée ! Au besoin, cliquez sur le bouton Signaler le message sur votre barre d'outils.


display the map name could be cool

The map name and the in-game date (month/week/day) are already displayed in the quick info window, which is shown when the right mouse button is pressed on the corresponding save file.

**Comment by ihhub** [comment] 2024-08-17 15:14
This is beyond the original game assets and to do this we need to rework the dialog.

**Comment by ihhub** [comment] 2024-09-07 05:16
Closing it as a duplicate of #4053.

**Closed by ihhub** 2024-09-07 05:16 UTC
Labels: improvement, assets
