### ISSUE TITLE
Escape to main menu from expansion campaign select-menu

### ISSUE THREAD

**Issue by Stisen1** [ihhub/fheroes2#7508] opened 2023-08-03 13:04 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

I want to be able to push the ESC-button and return to the main menu from the expansion campaign select screen? I seem to be forced to select one of them, skip the cinematics and then click the exit button.

### Describe the possible solution

Do some sort of replication of which menu windows the ESC-button press applies to.

**Comment by ihhub** [comment] 2023-09-17 04:22
@Stisen1 , isn't it the case with the Succession Wars campaign as well?

**Comment by ihhub** [comment] 2023-11-23 00:48
I am closing this issue as this is beyond the scope of even the original game and this is how the game was designed.

**Closed by ihhub** 2023-11-23 00:48 UTC
Labels: improvement, ui

**Comment by Branikolog** [comment] 2023-11-23 04:16
Hi, @ihhub !
I agree, that such behaviour doesn't exist in the original game. But I expect our engine remake being better in any way, regarding game logic and UI convenience.
Current behaviour is not really friendly, forcing player to choose something, while pressing "esc" button is a common and fast solution to return to previous menu, in a case player accidentally pressed wrong button.
I suggest going even further and allow to press the "esc" button at the campaign first briefing screen to return to campaign selection screen as player could select wrong campaign and there only way too change his choice is to exit and redo all steps too campaign selection.

**Comment by ihhub** [comment] 2023-11-23 05:42
Hi @Branikolog , considering the amount of work needed to implement this feature it is not worthy our effort. At very least we can create a discussion topic for this. Also take a note that rendering is affected for these screens as well: palette is different from the rest of the game.

**Comment by Branikolog** [comment] 2023-11-23 06:34
@ihhub 
Since when the difficulties of the implementation prohibit such improvements from being included in our "enhancements list"?

There could appear a kind contributor that could implement this with all his passion and hard work. ;)
