### ISSUE TITLE
Original files extraction for Linux systems

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4647] opened 2021-11-16 10:46 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Installation of fheroes2 using GOG version requires game files.

### Describe the possible solution

People owning GOG version need an instructions.

**Comment by ihhub** [comment] 2021-11-16 11:36
I don't think we should do this if it's complicated. This is OS specific thing and either should be addressed by a simple script or by nothing.

**Comment by Branikolog** [comment] 2021-11-16 11:53
Hi, @ihhub.
Can we at least point users inside the guide, that they have to extract needed folders manually? (If it's not implemented in our guide yet)

**Comment by oleg-derevenetz** [comment] 2021-11-16 12:30
I can try to make a script for that, but the problem is that it should be self-sufficient (no additional dependencies are allowed). I'll think about it.

**Closed** 2021-11-20 15:50 UTC
Labels: improvement, Linux
