### ISSUE TITLE
Combat, Berserker spell doesn't work as it should

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2249] opened 2020-11-19 18:19 UTC
In fheroes2, the Berserker spell doesn't work as it should.
The troop affected by the spell does not attack another troop when possible.

In fheroes2:

![Berserker fh2 01](https://user-images.githubusercontent.com/43583994/99706734-c9456d80-2a9b-11eb-9c4a-322b1b79e87f.png)

![Berserker fh2 02](https://user-images.githubusercontent.com/43583994/99706739-cb0f3100-2a9b-11eb-927d-f096da4cbf62.png)

Attack Ruby with Luna.
Cast the Berserker spell on Cyclops.
Skip the Red Dragons turn.
The Cyclops move but do not attack any troops.
Here is the save file:
[Bug berserk 01.zip](https://github.com/ihhub/fheroes2/files/5568868/Bug.berserk.01.zip)

Related issue: https://github.com/ihhub/fheroes2/issues/1017.

**Edit 2020/12/29.**

In fheroes2, the Berserker spell doesn't work like in the original game.
In fheroes2, per example, the spell is canceled when the berserk stack is physically attacked (melee attack, ranged attack), which should not happen.

The Berserker spell should work this way:
- the duration of the spell is egal to the hero's Spell Power (hero's Spell Power 3, spell duration 3 turns),
- the spell can be canceled by the Dispel Magic spells, the Cure spells and the Anti-Magic spell,
- the spell is canceled if the berserk stack performs an attack,
- the spell is not canceled when the berserk stack is physically attacked (melee attack, ranged attack), and the berserk stack retaliate,
- the spell is not canceled when the berserk stack takes damage from damage spells,
- if the troop under berserk is the only troop left in the hero's army, the hero cannot cast a spell.

**Comment by LeHerosInconnu** [comment] 2020-12-08 21:47
Here is another problem with the Berserker spell in fheroes2.

In this combat, both heroes are controlled by a human player.

Luna casts the Haste spell on the Phoenixes.
Astra casts the Berserker spell on the Phoenixes.

When the Phoenixes get the hand the next turn, the AI takes control of the hero and makes her cast a spell, as if the automatic combat mode was activated.

In fheroes2:
![Berserker AI 04](https://user-images.githubusercontent.com/43583994/101545161-22bc0080-39a7-11eb-90a4-81238a91c2f7.gif)

**Comment by LeHerosInconnu** [comment] 2020-12-08 23:27
In fheroes2, the Berserker spell doesn't work like in the original game.
In fheroes2, per example, the spell is canceled when the berserk stack is physically attacked (melee attack, ranged attack), which should not happen.

The Berserker spell should work this way:
- the duration of the spell is egal to the hero's Spell Power (hero's Spell Power 3, spell duration 3 turns),
- the spell can be canceled by the Dispel Magic spells, the Cure spells and the Anti-Magic spell,
- the spell is canceled if the berserk stack performs an attack,
- the spell is not canceled when the berserk stack is physically attacked (melee attack, ranged attack), and the berserk stack retaliate,
- the spell is not canceled when the berserk stack takes damage from damage spells.

**Comment by Branikolog** [comment] 2020-12-09 10:59
o_O Nice catch, @LeHerosInconnu!
Berzerker mode causes hero cast spell. ^_^
Could you use other spells that turn?

**Comment by LeHerosInconnu** [comment] 2020-12-09 21:48
@Branikolog.

> o_O Nice catch, @LeHerosInconnu!
> Berzerker mode causes hero cast spell. ^_^
> Could you use other spells that turn?

No, it was not possible for Luna to cast another spell during this turn, which makes sense.

**Comment by tau3** [comment] 2021-01-21 14:06
looks like the problem is wihin `void Battle::Arena::TurnTroop( Unit * current_troop )`: on Berserker spell a troop is marked as `CONTROL_AI` and `AI::Get().BattleTurn( *this, *current_troop, actions )` actually just ends turn (probably some smarter AI action like move + attack is required)

**Closed** 2021-01-21 16:46 UTC
Labels: bug, logic
