### ISSUE TITLE
Mouse cursor movement with 0.9 is badly broken 

### ISSUE THREAD

**Issue by vanfanel** [ihhub/fheroes2#2749] opened 2021-02-06 20:24 UTC
Hi there,

Just built 0.9 and noticed cursor movement is just erratic and "floaty", it does NOT match the movement of the mouse at all.
I have tried with FULLSCREEN mode, and it's the same.

0.8 was working fine. What has changed so dramatically?

**Comment by vanfanel** [comment] 2021-02-06 20:40
EDIT: There's also the problem that the cursor position is NOT registered correctly on the main menu. For example, to click any of the signs, I have to move the cursor WAY far from it :(

**Comment by vanfanel** [comment] 2021-02-06 21:05
Oops, it was my USB pad doing something funny with the mouse... closing this, sorry!

**Comment by karolchmist** [comment] 2021-04-23 12:21
Just in case it helps someone, here is a quick workaround. I had to disable my trackpoint to make `fheroes2` work on my laptop under Linux.

First, list all the input devices:
```
$ xinput 
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=10	[slave  pointer  (2)]
⎜   ↳ TPPS/2 IBM TrackPoint                   	id=13	[slave  pointer  (2)]
...
```

The disable the trackpoint:
```
xinput set-prop "TPPS/2 IBM TrackPoint" "Device Enabled" 0
```

Still, it would be great if the problem was fixed in the code... Can this issue be reopen?

**Comment by ihhub** [comment] 2021-04-24 02:59
Hi @karolchmist , by default fheroes2 detects any input device and then uses it as a default input. This was done as a part for consoles support. I think we can avoid this behavior for non-console builds.

**Comment by mmavova** [comment] 2021-04-29 19:46
> Just in case it helps someone, here is a quick workaround. I had to disable my trackpoint to make `fheroes2` work on my laptop under Linux. Tested on latest `master` branch (git commit: [a93d50e](https://github.com/ihhub/fheroes2/commit/a93d50ef11145a4449cad78e018e404a385e0f89)), with SDL2 enabled.
> 
> First, list all the input devices:
> 
> ```
> $ xinput 
> ⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
> ⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
> ⎜   ↳ SynPS/2 Synaptics TouchPad              	id=10	[slave  pointer  (2)]
> ⎜   ↳ TPPS/2 IBM TrackPoint                   	id=13	[slave  pointer  (2)]
> ...
> ```
> 
> Then disable the trackpoint:
> 
> ```
> xinput set-prop "TPPS/2 IBM TrackPoint" "Device Enabled" 0
> ```
> 
> Still, it would be great if the problem was fixed in the code... Can this issue be reopen?

I have the same issue, but there is no trackpoint:
```
xinput 
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Logitech Gaming Mouse G402              	id=8	[slave  pointer  (2)]
⎜   ↳ Logitech Gaming Mouse G402 Consumer Control	id=10	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Power Button                            	id=7	[slave  keyboard (3)]
    ↳ Logitech Gaming Mouse G402 Keyboard     	id=9	[slave  keyboard (3)]
    ↳ Logitech Gaming Mouse G402 System Control	id=11	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=12	[slave  keyboard (3)]
    ↳ Logitech Gaming Mouse G402 Consumer Control	id=13	[slave  keyboard (3)]
```

**Comment by mmavova** [comment] 2021-05-01 13:33
I used git bisect to find the commit that broke mouse support:

384a95de887b1ce8cbbb58690be234f6aee090c1 is the first bad commit
commit 384a95de887b1ce8cbbb58690be234f6aee090c1
Author: Taras <11291116+Northfear@users.noreply.github.com>
Date:   Sun Jan 3 16:33:01 2021 +0200

    Add game controller support (#2469)

:040000 040000 22d527365d06a2340420632120965c8d9c1c3295 7e30ff2415e230ff2f42a0610031b16764b78b02 M	src

**Comment by ihhub** [comment] 2021-05-04 00:56
Hi @Northfear , could you please take a look at this issue? The problem on PCs is that we automatically detect other devices.

**Comment by Northfear** [comment] 2021-05-04 06:57
@ihhub maybe we should enable touchpads/gamepads with separate game option (and set it on by default on Vita and Switch only)?
I'm pretty sure that touchpads are only useful on consoles and mobile anyway. And in rare cases some input devices can be recognized as gamepads by SDL too.
So it's either a new game option or a filter by the name of input device.

**Closed** 2021-05-06 13:30 UTC
Labels: bug, logic

**Comment by mmavova** [comment] 2021-05-06 13:54
Compiled git head with the latest patch. No change, it is still laggy for me.

**Comment by ihhub** [comment] 2021-05-06 14:08
Hi @mmavova , I found another place where software emulation for cursor is enabled. Soon the change will be merged,

**Comment by Northfear** [comment] 2021-05-06 14:12
@mmavova Give it a try. Seems to be working fine with Xbox Controller
https://github.com/Northfear/fheroes2-vita/tree/controller_disable

**Comment by karolchmist** [comment] 2021-06-03 08:20
The issue is fixed for me, thank you!
