### ISSUE TITLE
Adventure Map, Oracle screen, the information displayed in the Oracle screen is not complete

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1589] opened 2020-09-08 12:53 UTC
In the original game, when a hero visits the Oracle the complete information about all players is displayed.
In fheroes2, this is not the case.

In original game:

![Oracle 03](https://user-images.githubusercontent.com/43583994/92477560-1924d000-f1e1-11ea-982e-702f5da12638.png)

In fheroes2:

![Oracle 04](https://user-images.githubusercontent.com/43583994/92477396-d19e4400-f1e0-11ea-86b4-bc8533d0d088.png)

**Comment by idshibanov** [comment] 2020-10-07 09:24
Duplicate of issue #1150

**Comment by undef21** [comment] 2021-04-19 21:06
Hello. Is there any difference in information displayed in the Oralce, one thieves guild and two guilds?

**Comment by LeHerosInconnu** [comment] 2021-04-19 21:13
Hi @undef21,

> Hello. Is there any difference in information displayed in the Oralce, one thieves guild and two guilds?

The Thieves Guilds give more and more information according to the number of Thieves Guild built.

The Oracle gives all possible information.

**Comment by undef21** [comment] 2021-04-19 21:27
@LeHerosInconnu , which info should be displayed when player has 1 guild? when 2?

**Comment by LeHerosInconnu** [comment] 2021-04-19 21:39
@undef21.

> @LeHerosInconnu , which info should be displayed when player has 1 guild in OG? when 2?

Here is the information displayed with the Thieves Guild from 1 to 5.
From 5 and more, all the information is displayed.

In original game:

![Thieves Guild 001](https://user-images.githubusercontent.com/43583994/115306576-52a2be00-a168-11eb-9a7f-fc63ba4ab848.png)
![Thieves Guild 002](https://user-images.githubusercontent.com/43583994/115306585-55051800-a168-11eb-929a-362894a59cf6.png)
![Thieves Guild 003](https://user-images.githubusercontent.com/43583994/115306590-58000880-a168-11eb-89bf-211ec3ddf2b9.png)
![Thieves Guild 004](https://user-images.githubusercontent.com/43583994/115306597-5afaf900-a168-11eb-9eca-1b117ec9abed.png)
![Thieves Guild 005](https://user-images.githubusercontent.com/43583994/115306567-4f0f3700-a168-11eb-90cb-76da8ee347fe.png)

**Comment by undef21** [comment] 2021-04-23 08:12
@LeHerosInconnu, What is "Best Monster"? Is it best monster of displayed hero or best monster of kingdom?

**Comment by Branikolog** [comment] 2021-04-23 08:29
Hi, @undef21.
It's the best monster of kingdom.
Sorry, forgot about your question. )

**Comment by LeHerosInconnu** [comment] 2021-04-23 12:51
Hello @undef21 and @Branikolog,

> @LeHerosInconnu, What is "Best Monster"? Is it best monster of displayed hero or best monster of kingdom?

Yes, this is the best creature in the player's ranks (the best creature recruited, and not the best creature the player can recruit from one of his creature dwellings).

Also, for the Best Hero, it is not the hero with the best stats, but the hero with the most powerful army.

And the Best Hero Stats correspond to the stats of the Best Hero, so the hero with the most powerful army (so it is not really the stats of the hero with the best stats).

**Closed** 2021-05-04 13:31 UTC
Labels: bug, good first issue, ui
