### ISSUE TITLE
Adventure map, last hero dismissed, lose game window adjustment

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7092] opened 2023-05-01 13:27 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When a player dismisses his last hero when he has no village/castle left, he loses the game.
Note: The last hero cannot be dismissed in the original game.

The message displayed should be (text from screenshot of the original game):
Yellow title:
"Defeat!"

Text:
"You have been eliminated from the game!!!"

![Multiplayer mode player loses game H2 01](https://user-images.githubusercontent.com/43583994/93313330-a16e2b00-f808-11ea-8661-4ecc5099bac5.png)

Instead of (screenshots from fheroes2):

![Win lose game 006](https://user-images.githubusercontent.com/43583994/235457560-44e53c07-508b-4350-9025-8db019af8e57.png)
![Win lose game 007](https://user-images.githubusercontent.com/43583994/235457566-5fbc2fb3-2bce-4cfe-8f16-08f200e59bdd.png)

In fheroes2:

https://user-images.githubusercontent.com/43583994/235457617-586bb7d2-f9af-449d-ab25-803185dc7571.mp4

### Save file

Here are the save files:
[Last day 01.zip](https://github.com/ihhub/fheroes2/files/11365399/Last.day.01.zip)

**Comment by Alucard648** [comment] 2023-05-01 14:01
I think, "Defeat"/"Victory" caption should be also applied to all game-ending messages related to special win/loss conditions.

**Comment by oleg-derevenetz** [comment] 2023-05-01 19:07
This "You have been eliminated from the game!!!" message is shown in fheroes2 only in single-player mode. In OG, if you have no towns and lose your last hero in multi-player mode (e.g. in a battle), you see this message, that's true, BUT then you just sit with no heroes and no towns until you press the "end turn" button. At the time, I decided not to reproduce this weird behavior in fheroes2, your turn will be ended immediately instead and you'll get that "[color] player has been vanquished".

**Comment by ihhub** [comment] 2023-08-27 13:39
Hi @LeHerosInconnu , are we good to close this issue based on @oleg-derevenetz explanation?

**Comment by LeHerosInconnu** [comment] 2023-08-28 18:07
Hello @ihhub, @oleg-derevenetz and @Alucard648,

Here's what happens in the original game in different cases:

"Before eliminated single 01.GM1"
Human blue player.
The blue human player attacks and wins against the green AI player.
<details>
<summary> Screenshots: (click to expand)</summary>
<br>

![Eliminated message 001](https://github.com/ihhub/fheroes2/assets/43583994/3371a60e-0760-4744-85af-4ebdc6a2f50c)
![Eliminated message 002](https://github.com/ihhub/fheroes2/assets/43583994/150a87cb-cd65-4f99-9d9c-aadea8fcf822)
</details>

---
"Before eliminated single 02.GM1"
Human green player.
The green human player attacks and wins against the blue AI player.
<details>
<summary> Screenshots: (click to expand)</summary>
<br>

![Eliminated message 003](https://github.com/ihhub/fheroes2/assets/43583994/43f67266-b8f0-4fb8-a3b0-eb2d335e03ba)
![Eliminated message 004](https://github.com/ihhub/fheroes2/assets/43583994/851f05e9-b1eb-43f2-af9c-190635ae7812)
</details>

---
"Before eliminated single 03.GM1"
Human blue player.
The green AI player attacks and wins against the blue human player.
<details>
<summary> Screenshots: (click to expand)</summary>
<br>

![Eliminated message 020](https://github.com/ihhub/fheroes2/assets/43583994/7ff04743-0e4a-450a-b80f-9e5ab77a578a)
![Eliminated message 021](https://github.com/ihhub/fheroes2/assets/43583994/a9a78702-3c91-4806-97f9-05823814a52d)
![Eliminated message 022](https://github.com/ihhub/fheroes2/assets/43583994/ae326f02-d84a-427d-899b-0470829758ae)
</details>

---
"Before eliminated single 04.GM1"
Human green player.
The blue AI player attacks and wins against the green human player.
<details>
<summary> Screenshots: (click to expand)</summary>
<br>

![Eliminated message 023](https://github.com/ihhub/fheroes2/assets/43583994/f9cbae82-c816-47e5-99b7-554d8c5a1522)
![Eliminated message 024](https://github.com/ihhub/fheroes2/assets/43583994/d33837a0-66df-46c1-a838-19536c6e1ed4)
![Eliminated message 025](https://github.com/ihhub/fheroes2/assets/43583994/7077cf76-397d-4c05-a931-dc47c9436051)
</details>

---
"Before eliminated multi 01.GM2"
Human blue and green players.
The blue human player attacks and wins against the green human player.
<details>
<summary> Screenshots: (click to expand)</summary>
<br>

![Eliminated message 005](https://github.com/ihhub/fheroes2/assets/43583994/bfe672ba-a78b-477c-871c-0383764ed5f9)
![Eliminated message 006](https://github.com/ihhub/fheroes2/assets/43583994/a9a22a45-a96a-4e76-87bf-ea07937b23d0)
</details>

---
"Before eliminated multi 02.GM2"
Human blue and green players.
The green human player attacks and wins against the blue human player.
Here, the message is rather addressed to the blue human player, the first human player in the scenario.
<details>
<summary> Screenshots: (click to expand)</summary>
<br>

![Eliminated message 007](https://github.com/ihhub/fheroes2/assets/43583994/0a465319-22f3-4691-8ee9-a9a3bab6a715)
![Eliminated message 008](https://github.com/ihhub/fheroes2/assets/43583994/70bd5c93-09b9-421e-a16d-da68d6948d20)
</details>

---
"Before eliminated multi 03.GM2"
Human blue and green players.
The last hero of the blue human player cannot be dissmissed.
(This is improved in fheroes2.)
The blue human player attacks and loses against the green human player.
The victory screen is displayed, but it's more for the green human player.
<details>
<summary> Screenshots: (click to expand)</summary>
<br>

![Eliminated message 009](https://github.com/ihhub/fheroes2/assets/43583994/adba73b7-7f0a-40cb-b662-36339ef7ecd3)
![Eliminated message 026](https://github.com/ihhub/fheroes2/assets/43583994/58862449-8d84-4d4f-b4a8-c9abbea32c9a)
![Eliminated message 027](https://github.com/ihhub/fheroes2/assets/43583994/f6d31559-cb90-4159-a8dd-a5fb30337f76)
![Eliminated message 028](https://github.com/ihhub/fheroes2/assets/43583994/4fba74ae-77cd-405e-9805-a7e67e3170d7)
</details>

---
"Before eliminated multi 04.GM2"
Human blue and green players.
The green human player attacks and wins against the blue human player.
Here again, the message is rather addressed to the blue human player, the first human player in the scenario.
<details>
<summary> Screenshots: (click to expand)</summary>
<br>

![Eliminated message 010](https://github.com/ihhub/fheroes2/assets/43583994/7494278d-5305-40fa-bd3e-325d6ec47c98)
![Eliminated message 011](https://github.com/ihhub/fheroes2/assets/43583994/a30fd61a-d976-436b-885c-2d0f90757e2c)
</details>

---
"Before eliminated multi 05.GM2"
Human blue and green players.
The last hero of the green human player cannot be dissmissed.
(This is improved in fheroes2.)
The green human player attacks the blue human player and retreats.
Here again, the message is rather addressed to the blue human player, the first human player in the scenario.
<details>
<summary> Screenshots: (click to expand)</summary>
<br>

![Eliminated message 012](https://github.com/ihhub/fheroes2/assets/43583994/73b58e10-f214-4d0c-86d2-467704a275bb)
![Eliminated message 013](https://github.com/ihhub/fheroes2/assets/43583994/1d91defa-5232-4d6b-a23e-5e14b46efd9b)
![Eliminated message 014](https://github.com/ihhub/fheroes2/assets/43583994/3ea3c716-2ad7-4a4e-9362-2a3fed61fd74)
![Eliminated message 015](https://github.com/ihhub/fheroes2/assets/43583994/dcfe46f2-2abb-47be-b030-758320dfa5a7)
![Eliminated message 016](https://github.com/ihhub/fheroes2/assets/43583994/935debcb-85ed-4cfa-a89c-e68c42105f1e)
</details>

---
"Before eliminated multi 06.GM2"
Human blue and green players.
After seven days without owning a city, the human green player loses.
The blue human player wins at the start of his turn.
<details>
<summary> Screenshots: (click to expand)</summary>
<br>

![Eliminated message 017](https://github.com/ihhub/fheroes2/assets/43583994/159cc3dc-aa7c-446b-9a22-9505a80ed33b)
![Eliminated message 018](https://github.com/ihhub/fheroes2/assets/43583994/37fa9d41-65c9-44fb-ac1a-7af39c6d36bf)
![Eliminated message 019](https://github.com/ihhub/fheroes2/assets/43583994/1127435e-675a-4645-b7cd-a84342befddc)
</details>

---

Here are the save files:
[Before eliminated 01.zip](https://github.com/ihhub/fheroes2/files/12456826/Before.eliminated.01.zip)

The original game is not perfect in displaying messages, some of which don't seem to be addressed to the player on whose turn it is.

> This "You have been eliminated from the game!!!" message is shown in fheroes2 only in single-player mode. In OG, if you have no towns and lose your last hero in multi-player mode (e.g. in a battle), you see this message, that's true, BUT then you just sit with no heroes and no towns until you press the "end turn" button. At the time, I decided not to reproduce this weird behavior in fheroes2, your turn will be ended immediately instead and then there will be that "[color] player has been vanquished" message.

> ...BUT then you just sit with no heroes and no towns until you press the "end turn" button...

I have not experienced this case in the original game.
The end of the game proceeds normally by closing the last message window displayed.
Do you have a save file for this case?

> Hi @LeHerosInconnu , are we good to close this issue based on @oleg-derevenetz explanation?

I think the messages should be tailored to the player.
The "Major Event!" window tells the player that another player has been eliminated.
When the player who's playing loses the game, the message should be more personalized and indicate that it's a defeat for the current player, hence, in the case presented, the title of the window should be: "Defeat!" and the text (taken from the original game): "You have been eliminated from the game!!!".

> I think, "Defeat"/"Victory" caption should be also applied to all game-ending messages related to special win/loss conditions.

Yes, all this will have to be checked.
And other issues will be opened if necessary.

**Comment by oleg-derevenetz** [comment] 2023-08-28 18:35
> Human blue and green players.
The last hero of the green human player cannot be dissmissed.
(This is improved in fheroes2.)
The green human player attacks the blue human player and retreats.
Here again, the message is rather addressed to the blue human player, the first human player in the scenario.

OMG, this is so illogical. It turns out that sometimes "you have been eliminated from the game" message is shown and sometimes it is not shown. And sometimes it is even shown, but the game doesn't end for the human player (see video above). I don't think it's worth reproducing all this nonsense literally.

**Comment by LeHerosInconnu** [comment] 2023-08-28 20:13
@oleg-derevenetz.

> > I have not experienced this case in the original game.
> > The end of the game proceeds normally by closing the last message window displayed.
> > Do you have a save file for this case?
> 
> Take a look at this map for example:
> 
> [!BLKTST.zip](https://github.com/ihhub/fheroes2/files/12457150/BLKTST.zip)
> 
> Here is a video from the original game:
> 
> https://github.com/ihhub/fheroes2/assets/32623900/9101b035-7064-401c-aec9-199c306f4d92
> 
> This behavior is definitely not normal.
>
> P.S. It's also funny that in the original game the green hero is sitting in a neutral castle, but that's a different story...

The green player's hero is positioned in the neutral castle because, in the scenario editor, when a hero is positioned in front of the active castle square, he ends up in that castle at the start of the scenario (it is not possible to position a hero directly in a castle in the scenario editor).
The problem "comes from the scenario editor", where it should not be possible to position a hero directly in front of the entrance to a castle to avoid this oddity (or else allow a hero to be placed directly in a castle if the castle belong to the same player).
Or (better), the problem "comes from Heroes 2 program", which shouldn't put a hero in a castle if the castle doesn't belong to the player controlling the hero.
A conscientious scenario creator would notice this oddity during scenario testing and would adjust the scenario so that it doesn't happen.

Fheroes2 takes into account the fact that the neutral castle does not belong to the green player and does not place the green player's hero inside the neutral castle at the start of the scenario.

In the scenario editor, and in the original game:

![Wong position in editor to start scenario 001](https://github.com/ihhub/fheroes2/assets/43583994/bfd4afe8-137f-4248-b02c-148783503262)
![Wong position in editor to start scenario 002](https://github.com/ihhub/fheroes2/assets/43583994/fc1d9b80-ef67-488b-86ef-0c237fe42872)

In the scenario editor, and in fheroes2:

![Wong position in editor to start scenario 003](https://github.com/ihhub/fheroes2/assets/43583994/93356861-b17f-410d-a5d9-40cc453bd28b)
![Wong position in editor to start scenario 004](https://github.com/ihhub/fheroes2/assets/43583994/ba7cacf7-b23b-41b2-a7ab-0665bdfa4729)

---

![Wong position in editor to start scenario 001](https://github.com/ihhub/fheroes2/assets/43583994/bfd4afe8-137f-4248-b02c-148783503262)
![Wong position in editor to start scenario 006](https://github.com/ihhub/fheroes2/assets/43583994/62b983d5-a428-43a4-8c01-8fac7edc3be4)

**Comment by oleg-derevenetz** [comment] 2023-08-29 13:47
> The green player's hero is positioned in the neutral castle because, in the scenario editor, when a hero is positioned in front of the active castle square, he ends up in that castle at the start of the scenario (it is not possible to position a hero directly in a castle in the scenario editor).

Yes, I'm aware of this mechanics, I'm just a bit surprised at how this mechanic is handled in the original game. In general, fheroes2 now looks much more polished and logical game in many aspects compared to the original.

**Closed** 2023-08-30 00:35 UTC
Labels: bug, ui
