### ISSUE TITLE
Game, behaviour of AI heroes

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2499] opened 2020-12-27 19:31 UTC
In fheroes2, AI heroes do not perform actions intended to "diminish the effectiveness" of opposing heroes.

In the example, the hero Rialdo is a threat to the AI hero Kastore.
Kastore has already visited the Artesian Spring, certainly the previous week, because he has double his Spell Points during combat.
However, Kastore should visit the Artesian Spring even if he already has twice his Spell Points before going further away, to prevent Diablo from getting twice his Spell Points.
Without these extra Spell Points, Rialdo would not have been able to defeat Kastore's entire army (Kastore would have fled before).

In fheroes2:

![Rialdo artesian spring fh2 01](https://user-images.githubusercontent.com/43583994/103178332-3067f600-4882-11eb-85de-8ff7b043fc77.png)

![Rialdo artesian spring fh2 02](https://user-images.githubusercontent.com/43583994/103178334-32ca5000-4882-11eb-818d-2b682d67fa23.png)

![Rialdo artesian spring fh2 03](https://user-images.githubusercontent.com/43583994/103178336-352caa00-4882-11eb-8379-f806c7f7b752.png)

![Rialdo artesian spring fh2 04](https://user-images.githubusercontent.com/43583994/103178337-36f66d80-4882-11eb-8513-ed62ac852601.png)

![Rialdo artesian spring fh2 05](https://user-images.githubusercontent.com/43583994/103178338-38c03100-4882-11eb-9241-2ca25f99363e.png)

![Rialdo artesian spring fh2 06](https://user-images.githubusercontent.com/43583994/103178340-3b228b00-4882-11eb-8430-76339581b708.png)

Here are the save files (before and after):
[Game, behaviour of AI heroes.zip](https://github.com/ihhub/fheroes2/files/5745065/Game.behaviour.of.AI.heroes.zip)

**Comment by ihhub** [comment] 2023-08-20 14:38
I am closing this issue as duplicate of #7346

**Closed by ihhub** 2023-08-20 14:38 UTC
Labels: improvement, AI

**Comment by fheroes2bugs** [comment] 2023-09-22 20:14
How hard it is to improve the behavior?
I see, this is first issue, 29 dec 2020.

Other people already created duplicates #7346 #7410 #7774

**Comment by ihhub** [comment] 2023-09-22 23:43
Hi @fheroes2bugs , it's obviously not easy.
