### ISSUE TITLE
Ultimate artifact on the hill (not reachable)

### ISSUE THREAD

**Issue by SlavisaBelic** [ihhub/fheroes2#5766] opened 2022-08-19 15:36 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [ ] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I again and Ultimate Artifact issue on the newest version: 0.9.18. It is placed on the hill, what is not reachable field

### Save file

[trazim ultimate.zip](https://github.com/ihhub/fheroes2/files/9383354/trazim.ultimate.zip)
![ultimate](https://user-images.githubusercontent.com/108020889/185655194-c73a170c-c075-49f5-a331-1a35cd3d0a98.png)

**Comment by oleg-derevenetz** [comment] 2022-08-19 15:52
Hi @SlavisaBelic are you sure that this issue is reproducible on the **_latest snapshot build_**? Ultimate Artifacts shouldn't be placed behind tall objects (including mountains) after #5739.

**Comment by SlavisaBelic** [comment] 2022-08-19 16:53
Sorry, not it is just the newest released version from 8th August: 0.9.18 So, I assume this is solved

**Comment by ihhub** [comment] 2022-08-20 12:46
Hi @SlavisaBelic , can you please download the latest snapshot to verify it?

**Comment by oleg-derevenetz** [comment] 2022-08-20 12:54
> Hi @SlavisaBelic , can you please download the latest snapshot to verify it?

It will be hard to verify it, because the ultimate artifact placement is performed at the beginning of a new game. If an old savefile is loaded by a newer version of the game, the ultimate artifact position will not be changed.

**Comment by ihhub** [comment] 2022-08-21 07:25
I am closing this issue as it should be fixed by #5739. If it is not please reopen it.

**Closed by ihhub** 2022-08-21 07:25 UTC
Labels: bug, awaiting feedback
