### ISSUE TITLE
Font scaling

### ISSUE THREAD

**Issue by Shatur** [ihhub/fheroes2#6338] opened 2022-12-09 20:03 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

I play this game on a pocket handheld. The game works very well, but the font is small.

### Describe the possible solution

It would be great to be able to set font scaling. This is useful not only for handheld devices, but also for large monitors.

**Comment by Shatur** [comment] 2023-07-16 17:38
Here are some screenshots to see how small the text on handhelds like RG280V:
![-2147483648_-210070](https://github.com/ihhub/fheroes2/assets/22453358/60157c8e-e51d-4266-a4a3-affd788477b3)
![-2147483648_-210072](https://github.com/ihhub/fheroes2/assets/22453358/6c57587d-38d6-4626-9105-4699b855acb4)

**Comment by ihhub** [comment] 2023-08-20 15:09
I am closing this issue as we've added resolutions with scaling in the past. We cannot go smaller than 640x480 and the current font was designed for this resolution.

**Closed by ihhub** 2023-08-20 15:09 UTC
Labels: improvement, ui

**Comment by Shatur** [comment] 2023-08-20 15:47
@ihhub You probably misunderstood my suggestion. I'm not asking to make font smaller. I suggesting to add an option to make it larger independent of resolution.

**Comment by oleg-derevenetz** [comment] 2023-08-20 22:04
@Shatur Just making the font bigger is not enough. The text will no longer fit, it will start to fit on top of each other or on other control. This should be done in combination with dynamically resizeable interface, but this is unrealistic because all dialog boxes and interface elements are taken from the resources of the original game and many of them are in fact  pre-rendered static images with fixed-size fields where the text should be placed.

**Comment by Shatur** [comment] 2023-08-20 22:06
Oh, got it, thanks.
Sad, the game plays nice, but the text is barely readable.
