### ISSUE TITLE
Combat screen, cyclops corpse sprite is displayed on top of the crusader troop's creature count indicator

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#8800] opened 2024-06-02 13:58 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the cyclops corpse sprite is displayed on top of the crusader troop's creature count indicator.

In fheroes2:

![vlcsnap-2024-06-02-15h47m51s478](https://github.com/ihhub/fheroes2/assets/43583994/d164c9a9-a320-4861-9be7-792d127f05e3)

https://github.com/ihhub/fheroes2/assets/43583994/0434b08a-5e9e-49fb-81cb-77f436518aea

### Save file

Here is the save file:
[Siege corpse over count 02.zip](https://github.com/user-attachments/files/15525532/Siege.corpse.over.count.02.zip)

### Additional info

Related issue: https://github.com/ihhub/fheroes2/issues/8796.

**Comment by ihhub** [comment] 2024-06-28 15:00
Duplicate of #8410.

**Closed by ihhub** 2024-06-28 15:00 UTC
Labels: bug
