### ISSUE TITLE
ICN:X_LOC empty picture issue

### ISSUE THREAD

**Issue by BismarckDD** [ihhub/fheroes2#9348] opened 2024-12-17 14:06 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I am using demo version of HOMM2, but cannot get any pics of icn_id: ICN:X_LOC

 const fheroes2::Sprite & sprite = fheroes2::AGG::GetICN( ICN::X_LOC1, 0 );

![微信截图_20241217220431](https://github.com/user-attachments/assets/0a875af5-b634-4952-8234-76f90f96fc03)

### Save file

 const fheroes2::Sprite & sprite = fheroes2::AGG::GetICN( ICN::X_LOC1, 0 );

**Comment by ihhub** [comment] 2024-12-17 14:16
Hi @BismarckDD , you need to own an official PoL version of the game in order to have this resource. The demo version doesn't have it.

I am closing this issue as this is not a bug.

**Closed by ihhub** 2024-12-17 14:16 UTC
Labels: bug
