### ISSUE TITLE
Adventure map, player can summon a boat belonging to opponent

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4109] opened 2021-08-29 12:38 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

While playing multiplayer game one player disembarks, and the other player could summon the boat, that belongs to the first player.
![image](https://user-images.githubusercontent.com/55348946/131250564-8ec3a5ed-1b2a-4088-b9db-76f5a61ee9ef.png)
![image](https://user-images.githubusercontent.com/55348946/131250571-92a75c28-1869-42f4-94d6-04f33f1a777f.png)

### Save file

2 player hotseat save file.
[Summon Opponents boat.zip](https://github.com/ihhub/fheroes2/files/7072490/Summon.Opponents.boat.zip)

**Comment by gab** [comment] 2021-09-19 21:33
I'm pretty sure this is not a bug! I seem to remember being able to do that in the original. I believe boats are pretty much objects without a faction so they don't technically "belong" to anyone unless you're currently using it.

**Comment by Branikolog** [comment] 2021-09-22 12:50
Hello, @gab !
In the original game (both H2 and H3) we cannot summon a boat that was used by an opponent in the last time.
If we assume, that we can, so this could be easily abused, leaving any enemy hero disembarked alone on island forever.

**Comment by qarkai** [comment] 2021-09-22 15:33
I'm 100% sure it was in OG.
> this could be easily abused, leaving any enemy hero disembarked alone on island forever.

Happened to me.

**Comment by Branikolog** [comment] 2021-09-23 11:09
In the OG we CANNOT summon a boat that previously was used by enemy.
At the start of the game we can summon boat:
![image](https://user-images.githubusercontent.com/55348946/134496982-64327536-9b43-4da7-936f-e57a9def315b.png)
![image](https://user-images.githubusercontent.com/55348946/134497010-fd72469a-ba21-4f97-9c1c-a2ddfe2fe18a.png)
After AI used it and disembarked:
![image](https://user-images.githubusercontent.com/55348946/134496938-0e7ce6ed-cc58-486f-9f93-4e52a084f4af.png)

**Comment by qarkai** [comment] 2021-09-23 11:12
> CANNOT

Can't argue with shout. Bye.

**Comment by Branikolog** [comment] 2021-09-23 11:52
@qarkai 
I think screenshots are the most weighty argument, than caps lock. ;)

**Comment by gab** [comment] 2021-09-23 14:29
Well, those screenshots are convincing enough, I appreciate you took the time to document this @Branikolog . But it doesn't close the issue: does the summon interdiction last forever once the boat is used, or is there a turn limit or hero proximity rule for the "reservation"?  Our memories of boats being stolen have to come from somewhere.
(Also slightly off-topic, but I wonder how it was in Heroes 1. Could be the source of some hazy memories.)

**Comment by Branikolog** [comment] 2021-09-23 14:53
@gab, a boat is considered as belonging to a player, once he manually boarded on it. Until the moment other player boards on it. After that the first player cannot summon it anymore. 
(A boat that was neutral in the beginning of the game can be summoned by any player making it the property of that player, that's the original behaviour.)

**Comment by a1exsh** [comment] 2021-09-28 06:25
Hi!

I've checked the OG manual, but it doesn't say too much on the subject.  The most detailed account is provided by the in-game description of the spell:
![heroes2_000](https://user-images.githubusercontent.com/489601/135032722-c600072f-9057-4b61-8f3c-3878cbe5546f.png)

I hope that makes it absolutely clear that even if it was occasionally possible to summon another player's boat in OG, it was a mere bug.

**Comment by ihhub** [comment] 2022-11-26 11:11
Rising priority for this issue as this is an important piece of logic which breaks gameplay on some maps.

**Comment by Branikolog** [comment] 2023-02-16 14:37
> Here's an example of summon boat being abused to lock someone to an island: https://www.youtube.com/live/8kcMqaz2C6E?feature=share&t=1469

Boat stealing action. :)

**Closed** 2023-03-09 15:35 UTC
Labels: bug, logic, high priority
