### ISSUE TITLE
Adventure map, Water Wheel, New Week window, wrong title color

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1585] opened 2020-09-08 10:02 UTC
The title of this window should be yellow.
This window is displayed at the beginning of each new week when the option "world: Wind/Water Mills and Magic Garden can be captured" is enabled.

In fheroes2:

![Water wheel new week fh2 01](https://user-images.githubusercontent.com/43583994/92461258-5aa98100-f1c9-11ea-9dce-bfdac1c2363d.png)

**Comment by ihhub** [comment] 2021-08-02 00:14
Closing as duplicate of #2154.

**Closed by ihhub** 2021-08-02 00:14 UTC
Labels: help wanted, improvement, ui
