### ISSUE TITLE
AI crashes during their turn

### ISSUE THREAD

**Issue by pavel-janicek** [ihhub/fheroes2#6878] opened 2023-03-21 08:14 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

When ending turn, AI seems to try to cast Town Portal spell and then it crashes. Console log:
`fheroes2: /home/janipav/.cache/yay/fheroes2/src/fheroes2-1.0.2/src/fheroes2/ai/normal/ai_normal_hero.cpp:820: double AI::Normal::getGeneralObjectValue(const Heroes&, int, double, uint32_t) const: Assertion `0' failed.

fish: Job 1, 'fheroes2' terminated by signal SIGABRT (Abort)
`

### Save file

[4tears.MX2.zip](https://github.com/ihhub/fheroes2/files/11026136/4tears.MX2.zip)
[AUTOSAVE.zip](https://github.com/ihhub/fheroes2/files/11026140/AUTOSAVE.zip)

### Additional info

`fheroes2: /home/janipav/.cache/yay/fheroes2/src/fheroes2-1.0.2/src/fheroes2/ai/normal/ai_normal_hero.cpp:820: double AI::Normal::getGeneralObjectValue(const Heroes&, int, double, uint32_t) const: Assertion `0' failed.

**Comment by oleg-derevenetz** [comment] 2023-03-21 11:40
Could not reproduce this issue so far using the attached single-player `AUTOSAVE`. Is it always reproducible for you (just load `AUTOSAVE` and end the turn)?

**Comment by ihhub** [comment] 2023-03-21 14:11
Hi @pavel-janicek , are you using the latest snapshot?

**Comment by ihhub** [comment] 2023-03-21 14:47
Hi @oleg-derevenetz , I wasn't able neither.

**Comment by Nihlo** [comment] 2023-03-30 17:20
I think I got a similar issue. The game crashes with a c+ error during the ai-round. If I load the autosave it crashes again. 
Happend the first time. Standard skirmish game. Base map. Windows 10. 1.0.2

![h2](https://user-images.githubusercontent.com/26931653/228914862-571a3747-419a-4a23-af18-bbbe8e110b6d.jpg)

**Comment by oleg-derevenetz** [comment] 2023-03-30 18:46
> I think I got a similar issue.

Please try to install the latest [snapshot](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds) (NOT the latest release) and see if the issue has gone away.

**Comment by Nihlo** [comment] 2023-03-31 23:13
Yes the issue is gone. Played a few turns and everything seems to work normal again. Thanks

**Comment by oleg-derevenetz** [comment] 2023-03-31 23:18
I believe that this is a duplicate of (already fixed) #6862 and can be closed.

**Closed** 2023-03-31 23:19 UTC
Labels: bug, awaiting feedback
