### ISSUE TITLE
Adventure map Treasure Chest issue

### ISSUE THREAD

**Issue by saox** [ihhub/fheroes2#3834] opened 2021-07-12 06:23 UTC
- A taken treasure chests sprite does not dissapear in some cases
[fheroes2_bug.zip](https://github.com/ihhub/fheroes2/files/6798996/fheroes2_bug.zip)

**Comment by qarkai** [comment] 2021-07-12 08:57
First issue looks like duplicate of #3764.

**Comment by saox** [comment] 2021-07-12 08:58
@qarkai I updated the title and content so it only focuses on the other issue - a sprite remaining even though the Treasure Chest has been consumed

**Comment by oleg-derevenetz** [comment] 2021-07-12 10:02
> A taken treasure chests sprite does not dissapear in some cases

Aha, interesting... This chest is located behind the trees, so when the hero takes it, then the trees disappear instead of the chest.

**Comment by ihhub** [comment] 2021-07-12 12:41
This is well-known problem. We have to change the way how we remove / add objects on the map. We need to store a map of object IDs versus an array of tiles where an object is present and use this map to remove items instead of hacky way to blindly removing the first item in the queue.

**Closed** 2021-07-28 00:31 UTC
Labels: bug, logic, ui
