### ISSUE TITLE
Castle screen, upgraded and regular mausoleums have different alignment

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#8391] opened 2024-02-10 10:42 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

https://github.com/ihhub/fheroes2/assets/55348946/3cf680a6-cd83-44d4-9eaa-226524adfc56

When switching between castles a slight different is noticeable.

### Describe the possible solution

The initial part of the building shouldn't change its location after upgrade.

**Comment by ihhub** [comment] 2024-02-10 10:49
Closing this as a duplicate of #2059 .

**Closed by ihhub** 2024-02-10 10:49 UTC
Labels: improvement, ui
