### ISSUE TITLE
Ctrl to see enemy creature range

### ISSUE THREAD

**Issue by denierlexiese** [ihhub/fheroes2#8888] opened 2024-06-28 02:08 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Ability to hit control during fights and see the enemies walking distance.

### Describe the possible solution

Ability to hit control during fights and see the enemies walking distance.

**Comment by ihhub** [comment] 2024-06-28 14:52
Duplicate of #6527

**Closed by ihhub** 2024-06-28 14:52 UTC
Labels: improvement
