### ISSUE TITLE
 Magic book, no info window, when player makes a maintained right click over the bookmarks

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1285] opened 2020-08-19 16:51 UTC
In fheroes2, when the player makes a right-click and hold on the magic point number bookmark, an information window is displayed.
When the player releases the mouse button, the window remains displayed.
In the original game, if the player does the same action, the window is no longer displayed.

Also, in the original game, the mouse cursor is not displayed as long as the mouse button is held down.

In the original game:

![Magic book, info window 01](https://user-images.githubusercontent.com/43583994/90665625-95fd0380-e24c-11ea-8f93-bd2f8c224c5c.png)

In fheroes2:

![Magic book, info window 02](https://user-images.githubusercontent.com/43583994/90665653-9e553e80-e24c-11ea-8eeb-08ea4289556b.png)

Also, in the original game, an information window is displayed for the other two bookmarks.

In the original game:

![Magic book, info window 03](https://user-images.githubusercontent.com/43583994/90665667-a4e3b600-e24c-11ea-8f1c-342b38955e59.png)

![Magic book, info window 04](https://user-images.githubusercontent.com/43583994/90665681-aad99700-e24c-11ea-9876-ad4c2ff68d36.png)

**Comment by Branikolog** [comment] 2020-08-19 16:54
> In fheroes2, when the player makes a right-click and hold on the magic point number bookmark, an information window is displayed.
> When the player releases the mouse button, the window remains displayed.
> In the original game, if the player does the same action, the window is no longer displayed.

Was in #1087.

**Comment by LeHerosInconnu** [comment] 2020-08-19 17:15
You changed the title, but the window is displayed, and it should be displayed, just it should not be displayed when the user releases the mouse button.
The title no longer corresponds to a part of the reported issue.

**Comment by Branikolog** [comment] 2020-08-19 18:08
An issue regarding a window with "okay" button appear after a right click is already exists. ( #1087)
But I didn't knew, that other bookmarks have also info windows in OG.
So I tried to change this thread into the separate one, about missing info of other bookmarks.

**Comment by Branikolog** [comment] 2020-08-19 18:10
Sorry, for acting on my own. If you wish, i can PM you in a case you've created duplicate of an existing issue, so you can change your topic by yourself.

**Comment by LeHerosInconnu** [comment] 2020-08-19 18:44
@Branikolog.

Don't worry. :)
And there's no point in sending me a private message, as long as there is no need to revamp the message in depth.

**Closed** 2020-09-22 16:05 UTC
Labels: bug, ui
