### ISSUE TITLE
Battle: improve behavior when ghosts are in the team

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#8182] opened 2023-12-25 20:21 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

At the moment, computer tries to win battle as fast as he can. Good strategy, but not the best when the ghosts are in team.
After the battle (computer plays) I have 24 ghosts:

https://github.com/ihhub/fheroes2/assets/145407420/8d904013-af63-48d6-902f-ed95f5244c66

It would be better to skip turn for non-ghosts stacks, so after the battle, it could be 34 ghosts (I play):

https://github.com/ihhub/fheroes2/assets/145407420/a17ce2db-b96e-4617-b6ce-3b53115de6fe

### Describe the possible solution

make units to skip turn, so ghosts can kill more units

### Additional info

version 1.0.11

Save: 
[ghosts improve.zip](https://github.com/ihhub/fheroes2/files/13767192/ghosts.improve.zip)

**Comment by ihhub** [comment] 2024-04-13 05:14
Closing this as a duplicate of #7685 .

**Closed by ihhub** 2024-04-13 05:14 UTC
Labels: improvement, AI
