### ISSUE TITLE
Missing translation string for SELECT button.

### ISSUE THREAD

**Issue by Mr-Bajs** [ihhub/fheroes2#6932] opened 2023-04-01 21:04 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Describe the bug

This button seems not to be translatable, can't find it in the .po file and no language seems to have translated it.

![SelectButton](https://user-images.githubusercontent.com/93934125/229313754-56fa382e-4ac3-4418-8f4d-4bcf0f3720b7.png)

**Comment by ihhub** [comment] 2023-04-02 01:57
This is a duplicate of #6105. There is no need to create separate tasks for individual buttons.

**Closed by ihhub** 2023-04-02 01:57 UTC
Labels: bug
