### ISSUE TITLE
7-zip detection in bat files for Windows is incorrect

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#211] opened 2019-10-29 08:13 UTC
Some users noticed that on Windows OS without installed 7-zip archiver script still goes to logic to unpack packages as well as copy file:
```
"""" is not an external or internal command.
```

The root of problem most likely lies in `if not sevenZipPath == "" (` line. I think we need to replace it by `if not "%sevenZipPath%" == "" (`.

**Comment by ihhub** [comment] 2019-10-29 08:14
Hi @PalashBansal, would you mind to take a look into this issue?

**Comment by PalashBansal** [comment] 2019-10-29 08:46
I didn't get this error, may be because i have 7z installed
I tried to simulate using below script-
```
@echo off
set sevenZipPath=

REM 8z should not be found
where 8z.exe >nul 2>nul
if %errorlevel% == 0 (
    set sevenZipPath=8z.exe
	echo "should not print 1"
) else (
    if exist "%ProgramFiles%\7-Zip\8z.exe" (
        set sevenZipPath=%ProgramFiles%\7-Zip\8z.exe
		echo "should not print 2"
    )
)

if not sevenZipPath == "" (
echo "should not print 3(error simulated)"
) else (
echo "error not reproducible"
)
pause >nul
```
and issue is partially reproducible.
i am not getting error you stated- `"""" is not an external or internal command.`
but found that script going inside `if` statement it is not meant to(in case 8z is not there)
After changing to your suggested changes `if not "%sevenZipPath%" == "" (`, it works fine.

**Comment by PalashBansal** [comment] 2019-10-29 09:15
Resolved in https://github.com/ihhub/fheroes2/pull/196

**Closed** 2019-10-29 13:38 UTC
Labels: Windows, script
