### ISSUE TITLE
Screen moves a bit after visiting some objects

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#885] opened 2020-06-25 20:25 UTC
When hero visits any object, which has pop up window, when we close that window screen moves a few pixels to the direction hero made his last move. 
(On a screen hero visited windmill standing to the right from it)
![move](https://user-images.githubusercontent.com/55348946/85791768-0ef34980-b73b-11ea-9405-e7452d463169.jpg)
![move2](https://user-images.githubusercontent.com/55348946/85791771-1155a380-b73b-11ea-9062-4d01feb7df69.jpg)

**Comment by idshibanov** [comment] 2020-07-11 01:51
`hero.Action()` happens first before we return from the move function and do a final camera recenter.

**Comment by LeHerosInconnu** [comment] 2020-10-04 08:08
Hello @ihhub,

I tried the latest version of fheroes2 (1895).
The hero's jump, although less, is still visible.

Why not let the hero take his final position and center the map at the same time before opening the window?
This would avoid re-centering the map after closing the window.

**Comment by ihhub** [comment] 2020-10-04 08:10
Hi @LeHerosInconnu , it is correct. The issue is still present, that's why I didn't close it.

The problem lies in a very bad code design of the original project so it's not easy to fix this issue :)

**Comment by LeHerosInconnu** [comment] 2020-10-04 08:19
@ihhub.

> Hi @LeHerosInconnu , it is correct. The issue is still present, that's why I didn't close it.
> 
> The problem lies in a very bad code design of the original project so it's not easy to fix this issue :)

Okay, thanks for the clarification. :)

**Closed** 2021-06-06 14:58 UTC
Labels: bug, help wanted, ui
