### ISSUE TITLE
Castle screen, heroes in tavern could change if AI player hires them in its turn

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3662] opened 2021-06-10 11:42 UTC
Seems that AI has same heroes for hire in tavern. That's why hero in tavern of a player could disappear.
First day.
![image](https://user-images.githubusercontent.com/55348946/121518470-2fbeb880-c9f9-11eb-9b21-1d1cdf93a8d0.png)

Second day.
![image](https://user-images.githubusercontent.com/55348946/121518964-c55a4800-c9f9-11eb-8277-e5ce6eb1943d.png)
[Hero poll.zip](https://github.com/ihhub/fheroes2/files/6631004/Hero.poll.zip)

**Comment by felix642** [comment] 2021-08-21 15:54
Hi @Branikolog I'm not quite sure to understand what's the issue here. Could you please give a bit more details of the desired behaviour?

**Comment by Branikolog** [comment] 2021-08-21 16:24
Hello, @felix642 
As you could see on a screenshots, two different days within one week offer different heroes for hire. I haven't bought one, but second day hero has changed. 
This could happen any day. But sometimes everything is OK. I suppose AI player managed to buy a hero, which appeared in his tavern. The hero, that is also available for hire in my tavern.. 
To reproduce the issue, try to load any map with all factions of the same type. Check tavern: there you could find at least one hero if your faction. Then skip your turn. 99% next day there will be another hero.

**Comment by a1exsh** [comment] 2021-09-04 08:19
@Branikolog I don't understand what's the issue here.  Are you trying to suggest that the AI should be offered other heroes to hire?  Why is that?  Is this how it works in the original game?

By the way, what about hot seat?  Should each player be offered different set of heroes?

**Comment by a1exsh** [comment] 2021-09-04 08:36
Just checked in OG and in fheroes2.

1. Each human player has a different choice of heroes to hire in both games.
2. Computer players seem to have a separate choice as well in both games.

I wasn't able to reproduce the issue with the version built from the latest source code so far.  Maybe it got fixed recently?

**Comment by Branikolog** [comment] 2021-09-04 11:14
Hi, @a1exsh 
The issue is reproduceable now.
On Monday we are able to hire Lord Killburn the Knight in the upper slot. But when we end turn, on Tuesday he was changed by the Fineous the Barbarian. All heroes in tavern shouldn't change the whole week.

**Comment by a1exsh** [comment] 2022-01-30 19:07
@oleg-derevenetz @ihhub FYI: the issue is still there after the fix.  Just started a game, checked the heroes for hire and on the next day one of them is different (most likely got hired by AI).

**Comment by oleg-derevenetz** [comment] 2022-01-30 19:10
@a1exsh

> @oleg-derevenetz @ihhub FYI: the issue is still there after the fix. Just started a game, checked the heroes for hire and on the next day one of them is different (most likely got hired by AI).

Yes, because it is [observed](https://github.com/ihhub/fheroes2/pull/4931#issuecomment-1016782256) in the OG as well. This is not a bug. In general, you can't always have distinct recruits in each kingdom because there is not enough heroes in the game for that.

**Comment by a1exsh** [comment] 2022-01-30 19:27
> This is not a bug.

Hm, it's a bit surprising to see this issue on the second day of a game, don't you think?..  The scenario I was starting is 2nd in the "Price of Loyalty" extended campaign.

**Comment by oleg-derevenetz** [comment] 2022-01-30 19:30
@a1exsh

> Hm, it's a bit surprising to see this issue on the second day of a game, don't you think?.. The scenario I was starting is 2nd in the "Price of Loyalty" extended campaign.

> I'd say, the more free heroes there are, the less likely this is, but this probability is always there.

**Comment by a1exsh** [comment] 2022-01-30 19:34
@oleg-derevenetz alright, no big deal — will keep in mind to grab the hero I like without waiting for AI to do the same.  Thanks for explaining! :)

**Comment by oleg-derevenetz** [comment] 2022-01-30 19:37
@a1exsh

> @oleg-derevenetz alright, no big deal — will keep in mind to grab the hero I like without waiting for AI to do the same. Thanks for explaining! :)

BTW AI can't hire heroes you get as a reward, so they will be available in tavern the whole first week.

**Comment by oleg-derevenetz** [comment] 2022-01-30 19:53
Let's reopen this issue for a while. Although in general it is impossible to always have a different set of heroes for hire in all kingdoms (this would require 6x(8+2)=60 heroes, while we have just 54 minus heroes reserved for jails), but maybe we will be able to add some heuristics for the case when there is enough free heroes.

**Comment by oleg-derevenetz** [comment] 2022-01-31 10:33
Hi @Branikolog

> What about other weeks? I hope with current logic player won't be able to hire that special reward heroes other weeks by accident...

AI can't hire "special" heroes at all.

> Or will this heroes be in human's hero pool till the end of the game?

Currently heroes offered as a campaign reward are available for hire for the human player only during the first week. Then they will replaced by the pair of "regular" heroes and will never come to the tavern again.

**Comment by Branikolog** [comment] 2022-01-31 10:37
@oleg-derevenetz 
Good to hear, that everything regarding this logic works well! :)

**Closed** 2022-02-04 03:11 UTC
Labels: bug, help wanted, ui
