### ISSUE TITLE
'Replay Opponent Turn' New Button

### ISSUE THREAD

**Issue by denierlexiese** [ihhub/fheroes2#8887] opened 2024-06-28 00:49 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Like HOMM3, use the replace turn button to review the last turn.

### Describe the possible solution

Like HOMM3, use the replace turn button to review the last turn.

**Comment by ihhub** [comment] 2024-06-28 14:56
Duplicate of #1330.

**Closed by ihhub** 2024-06-28 14:56 UTC
Labels: improvement
