### ISSUE TITLE
AI sits in the castle despite treasure chests and an endless gold sack are nearbý.

### ISSUE THREAD

**Issue by kitovyj** [ihhub/fheroes2#7410] opened 2023-07-14 19:44 UTC
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Green ally sits in its last castle for many turns despite that it can collect treasure chests nearby and come back during the same turn(?).

### Save file

[New_Enemies_0037.zip](https://github.com/ihhub/fheroes2/files/12053481/New_Enemies_0037.zip)

**Comment by oleg-derevenetz** [comment] 2023-07-15 11:29
> despite that it can collect treasure chests nearby and come back during the same turn(?)

This functionality is not yet implemented (see #7346). So if AI hero has a priority task to defend a castle, he will sit inside until the threat to the castle disappears.

**Comment by kitovyj** [comment] 2023-09-09 11:30
I think this and many similar issues of stragetic AI can be solved by classic chess-AI approach - enumeration of all possible actions/action chains during the same turn and selecting the chain giving the best target function(the 'score' of the strategic situation in the end of the chain)  value. It will solve various "hero boards a boat ignoring a treasure chest it can grab before the boarding  / hero runs toward a castle ignoring enemy hero it passes by etc). It will hurt the computation time of AI moves of course. I think making manual patches directly programming logic in every specific situation can make the code very complicated and unmaintainable.

**Comment by oleg-derevenetz** [comment] 2023-09-09 12:41
> It will hurt the computation time of AI moves of course.

Suppose we have a large map (144x144 = 20736 tiles). Suppose that 1/50 of these tiles are tiles with objects, it's about 400 objects. The number of options with visits to them in different order (which the AI should calculate in planning mode, because it takes into account all available objects) is 400!, which is ~6*10^868. Even if there are only 100 objects on the map, the number of options for visiting them in different order will be about 10^158.

**Comment by kitovyj** [comment] 2023-09-09 12:50
> > It will hurt the computation time of AI moves of course.
> 
> Suppose we have a large map (144x144 = 20736 tiles). Suppose that 1/50 of these tiles are tiles with objects, it's about 400 objects. The number of options with visits to them in different order (which the AI should calculate in planning mode, because it takes into account all available objects) is 400!, which is ~6*10^868. Even if there are only 100 objects on the map, the number of options for visiting them in different order will be about 10^158.

Hmm, yes, more than thought relying on intuition) But what if we consider just 'all nearby objects for complete permutation+ all distant castles as the final object in the chain'. Then, say, there are around 5 nearby targets and 10 distant castles. Then we end up with (5! + 10) * number_of_heroes which sounds sane?

**Comment by ihhub** [comment] 2024-10-27 11:27
Closing this issue as duplicate of #7346.

**Closed by ihhub** 2024-10-27 11:27 UTC
Labels: improvement, AI
